//
// Code generated by api/cmd/gen-relationships. DO NOT EDIT.
//
// Source of truth: api/configs/relationship-types.yaml
// Run `make generate-relationships` (from the api/ directory) to regenerate.

import type { ExtendedAssetType } from './relationship.types'

// =============================================================================
// Relationship Type Union
// =============================================================================

export type GeneratedRelationshipType =
  | 'runs_on'
  | 'deployed_to'
  | 'contains'
  | 'exposes'
  | 'member_of'
  | 'resolves_to'
  | 'depends_on'
  | 'sends_data_to'
  | 'stores_data_in'
  | 'authenticates_to'
  | 'granted_to'
  | 'load_balances'
  | 'protected_by'
  | 'monitors'
  | 'manages'
  | 'owned_by'

// =============================================================================
// Labels
// =============================================================================

export interface GeneratedRelationshipLabel {
  direct: string
  inverse: string
  description: string
  category: string
}

export const GENERATED_RELATIONSHIP_LABELS: Record<
  GeneratedRelationshipType,
  GeneratedRelationshipLabel
> = {
  runs_on: {
    direct: 'Runs On',
    inverse: 'Runs',
    description:
      'Runtime location of a workload — service/container/website is currently executing on this compute. Use this for "where it lives now". For build/deploy events use Deployed To.',
    category: 'attack_surface_mapping',
  },
  deployed_to: {
    direct: 'Deployed To',
    inverse: 'Has Deployment',
    description:
      'Build artifact placed at a target — strictly for repos / container images / build outputs. Do NOT use this for runtime workloads (those use Runs On).',
    category: 'attack_surface_mapping',
  },
  contains: {
    direct: 'Contains',
    inverse: 'Contained By',
    description:
      'Hierarchical parent-child relationship (org → app → service; cluster → namespace).',
    category: 'attack_surface_mapping',
  },
  exposes: {
    direct: 'Exposes',
    inverse: 'Exposed By',
    description: 'Asset exposes an access surface (api/service → port/endpoint/public interface).',
    category: 'attack_surface_mapping',
  },
  member_of: {
    direct: 'Member Of',
    inverse: 'Has Member',
    description:
      'Membership in a group or collection (user → group; host → cluster; namespace → cluster).',
    category: 'attack_surface_mapping',
  },
  resolves_to: {
    direct: 'Resolves To',
    inverse: 'Resolved By',
    description: 'DNS resolution (domain/subdomain → IP/CDN/load balancer).',
    category: 'attack_surface_mapping',
  },
  depends_on: {
    direct: 'Depends On',
    inverse: 'Used By',
    description: 'A needs B to function (service → database; web_app → api).',
    category: 'attack_path_analysis',
  },
  sends_data_to: {
    direct: 'Sends Data To',
    inverse: 'Receives Data From',
    description: 'Data flow in-transit (service → service; producer → queue).',
    category: 'attack_path_analysis',
  },
  stores_data_in: {
    direct: 'Stores Data In',
    inverse: 'Stores Data For',
    description: 'Data at-rest (service/app → database/bucket/data store).',
    category: 'attack_path_analysis',
  },
  authenticates_to: {
    direct: 'Authenticates To',
    inverse: 'Authenticates',
    description: 'Authentication relationship (user/service → IdP/app/api).',
    category: 'attack_path_analysis',
  },
  granted_to: {
    direct: 'Granted To',
    inverse: 'Has Grant',
    description: 'IAM privilege (role/policy → principal/resource).',
    category: 'attack_path_analysis',
  },
  load_balances: {
    direct: 'Load Balances',
    inverse: 'Load Balanced By',
    description: 'Traffic distribution (load_balancer → service/web_app).',
    category: 'attack_path_analysis',
  },
  protected_by: {
    direct: 'Protected By',
    inverse: 'Protects',
    description: 'Security control (web_app → WAF; host → EDR; cloud → CSPM).',
    category: 'control_and_ownership',
  },
  monitors: {
    direct: 'Monitors',
    inverse: 'Monitored By',
    description: 'Observability (SIEM/EDR/APM → asset).',
    category: 'control_and_ownership',
  },
  manages: {
    direct: 'Manages',
    inverse: 'Managed By',
    description: 'Control-plane management (cloud_account/IAM → resource/workload).',
    category: 'control_and_ownership',
  },
  owned_by: {
    direct: 'Owned By',
    inverse: 'Owns',
    description: 'Accountability (asset → team/owner).',
    category: 'control_and_ownership',
  },
}

// =============================================================================
// Constraints
// =============================================================================

export interface GeneratedRelationshipConstraint {
  sourceTypes: ExtendedAssetType[]
  targetTypes: ExtendedAssetType[]
}

export const GENERATED_RELATIONSHIP_CONSTRAINTS: Record<
  GeneratedRelationshipType,
  GeneratedRelationshipConstraint[]
> = {
  runs_on: [
    {
      sourceTypes: ['service', 'api', 'website'],
      targetTypes: ['host', 'container', 'k8s_workload', 'cloud_account'],
    },
    {
      sourceTypes: ['database'],
      targetTypes: ['host', 'container', 'cloud_account'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['k8s_cluster'],
    },
    {
      sourceTypes: ['container'],
      targetTypes: ['host', 'k8s_workload'],
    },
  ],
  deployed_to: [
    {
      sourceTypes: ['repository', 'container_image'],
      targetTypes: ['k8s_cluster', 'k8s_workload', 'cloud_account', 'host'],
    },
  ],
  contains: [
    {
      sourceTypes: ['k8s_cluster'],
      targetTypes: ['k8s_workload'],
    },
    {
      sourceTypes: ['api_collection', 'api'],
      targetTypes: ['api_endpoint'],
    },
    {
      sourceTypes: ['host'],
      targetTypes: ['container', 'service', 'database'],
    },
    {
      sourceTypes: ['repository'],
      targetTypes: ['container_image'],
    },
    {
      sourceTypes: ['network'],
      targetTypes: ['host', 'cloud_account', 'load_balancer'],
    },
    {
      sourceTypes: ['cloud_account'],
      targetTypes: ['host', 'database', 'k8s_cluster', 'network', 'storage', 'serverless'],
    },
  ],
  exposes: [
    {
      sourceTypes: ['host', 'k8s_workload', 'container'],
      targetTypes: ['api_endpoint', 'service', 'api'],
    },
    {
      sourceTypes: ['domain'],
      targetTypes: ['website', 'api', 'service'],
    },
    {
      sourceTypes: ['load_balancer'],
      targetTypes: ['api', 'service', 'website'],
    },
  ],
  member_of: [
    {
      sourceTypes: ['host', 'container', 'k8s_workload'],
      targetTypes: ['k8s_cluster', 'network'],
    },
    {
      sourceTypes: ['service', 'api'],
      targetTypes: ['network'],
    },
  ],
  resolves_to: [
    {
      sourceTypes: ['domain'],
      targetTypes: ['ip_address', 'load_balancer', 'cloud_account', 'host'],
    },
  ],
  depends_on: [
    {
      sourceTypes: ['service', 'api', 'website'],
      targetTypes: ['database', 'api', 'service', 'credential'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['container_image', 'database', 'api', 'service'],
    },
    {
      sourceTypes: ['mobile'],
      targetTypes: ['api', 'service'],
    },
  ],
  sends_data_to: [
    {
      sourceTypes: ['service', 'api', 'website', 'mobile'],
      targetTypes: ['database', 'api', 'service', 'cloud_account'],
    },
    {
      sourceTypes: ['database'],
      targetTypes: ['database'],
    },
  ],
  stores_data_in: [
    {
      sourceTypes: ['service', 'api', 'website'],
      targetTypes: ['database', 'storage', 'cloud_account'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['database', 'storage'],
    },
  ],
  authenticates_to: [
    {
      sourceTypes: ['api', 'service', 'website', 'mobile'],
      targetTypes: ['identity_provider', 'service', 'api'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['identity_provider', 'service'],
    },
  ],
  granted_to: [
    {
      sourceTypes: ['credential', 'service'],
      targetTypes: ['cloud_account', 'database', 'api', 'service', 'k8s_cluster'],
    },
  ],
  load_balances: [
    {
      sourceTypes: ['load_balancer', 'service', 'cloud_account'],
      targetTypes: ['host', 'k8s_workload', 'service', 'container'],
    },
  ],
  protected_by: [
    {
      sourceTypes: ['website', 'api', 'service'],
      targetTypes: ['load_balancer', 'service'],
    },
    {
      sourceTypes: ['host', 'compute'],
      targetTypes: ['service'],
    },
    {
      sourceTypes: ['cloud_account'],
      targetTypes: ['service'],
    },
  ],
  monitors: [
    {
      sourceTypes: ['service'],
      targetTypes: [
        'host',
        'k8s_cluster',
        'cloud_account',
        'api',
        'service',
        'database',
        'network',
      ],
    },
  ],
  manages: [
    {
      sourceTypes: ['cloud_account'],
      targetTypes: ['host', 'database', 'k8s_cluster', 'network', 'load_balancer'],
    },
    {
      sourceTypes: ['k8s_cluster'],
      targetTypes: ['k8s_workload', 'container'],
    },
  ],
  owned_by: [
    {
      sourceTypes: [
        'domain',
        'website',
        'service',
        'repository',
        'cloud_account',
        'host',
        'database',
        'api',
        'mobile',
        'k8s_cluster',
      ],
      targetTypes: ['service'],
    },
  ],
}

// =============================================================================
// Categories (display order)
// =============================================================================

export interface GeneratedRelationshipCategory {
  id: string
  name: string
}

export const GENERATED_RELATIONSHIP_CATEGORIES: GeneratedRelationshipCategory[] = [
  { id: 'attack_surface_mapping', name: 'Attack Surface Mapping' },
  { id: 'attack_path_analysis', name: 'Attack Path Analysis' },
  { id: 'control_and_ownership', name: 'Control & Ownership' },
]

// =============================================================================
// Convenience: ordered ID list
// =============================================================================

export const ALL_GENERATED_RELATIONSHIP_TYPES: GeneratedRelationshipType[] = [
  'runs_on',
  'deployed_to',
  'contains',
  'exposes',
  'member_of',
  'resolves_to',
  'depends_on',
  'sends_data_to',
  'stores_data_in',
  'authenticates_to',
  'granted_to',
  'load_balances',
  'protected_by',
  'monitors',
  'manages',
  'owned_by',
]
