//
// Code generated by api/cmd/gen-relationships. DO NOT EDIT.
//
// Source of truth: api/configs/relationship-types.yaml
// Run `make generate-relationships` (from the api/ directory) to regenerate.

import type { ExtendedAssetType } from './relationship.types'

// =============================================================================
// Relationship Type Union
// =============================================================================

export type GeneratedRelationshipType =
  | 'runs_on'
  | 'deployed_to'
  | 'contains'
  | 'exposes'
  | 'resolves_to'
  | 'cname_of'
  | 'depends_on'
  | 'peer_of'
  | 'replicates_to'
  | 'sends_data_to'
  | 'stores_data_in'
  | 'authenticates_to'
  | 'granted_to'
  | 'has_access_to'
  | 'load_balances'
  | 'protected_by'
  | 'monitors'
  | 'manages'

// =============================================================================
// Labels
// =============================================================================

export interface GeneratedRelationshipLabel {
  direct: string
  inverse: string
  description: string
  category: string
}

export const GENERATED_RELATIONSHIP_LABELS: Record<
  GeneratedRelationshipType,
  GeneratedRelationshipLabel
> = {
  runs_on: {
    direct: 'Runs On',
    inverse: 'Runs',
    description:
      'Runtime location of a workload — service/container/website is currently executing on this compute. Use this for "where it lives now". For build/deploy events use Deployed To.',
    category: 'attack_surface_mapping',
  },
  deployed_to: {
    direct: 'Deployed To',
    inverse: 'Has Deployment',
    description:
      'Build artifact placed at a target — strictly for repos / container images / build outputs. Do NOT use this for runtime workloads (those use Runs On).',
    category: 'attack_surface_mapping',
  },
  contains: {
    direct: 'Contains',
    inverse: 'Contained By',
    description:
      'Hierarchical parent-child relationship. The single direction we use for ALL hierarchical edges (cluster→workload, host→container, cloud_account→host, etc). Always source = parent, target = child. Do NOT model the inverse as a separate edge.',
    category: 'attack_surface_mapping',
  },
  exposes: {
    direct: 'Exposes',
    inverse: 'Exposed By',
    description: 'Asset exposes an access surface (api/service → port/endpoint/public interface).',
    category: 'attack_surface_mapping',
  },
  resolves_to: {
    direct: 'Resolves To',
    inverse: 'Resolved By',
    description:
      'Literal DNS A/AAAA resolution — a domain resolves to an IP record or a load balancer that owns that IP. STRICT semantic: target MUST be the network endpoint, not the server that happens to own the IP. For "this domain leads to this server / website" use Exposes. For subdomain → parent domain or CNAME aliases use Cname Of.',
    category: 'attack_surface_mapping',
  },
  cname_of: {
    direct: 'CNAME Of',
    inverse: 'Has CNAME',
    description:
      'DNS aliasing — this name is a CNAME for that name. Also used for subdomain → parent domain logical relationships. Distinct from Resolves To which captures the final IP/host record.',
    category: 'attack_surface_mapping',
  },
  depends_on: {
    direct: 'Depends On',
    inverse: 'Used By',
    description:
      'A needs B to function (service → database; web_app → api). Use for hard runtime dependencies, NOT for peer relationships (use Peer Of) or replication (use Replicates To).',
    category: 'attack_path_analysis',
  },
  peer_of: {
    direct: 'Peer Of',
    inverse: 'Peer Of',
    description:
      'Symmetric relationship between equal-rank assets — sibling services in a cluster, HA pairs, leader/follower nodes. Pick EITHER asset as source; the inverse direction is implied. Do NOT model the same pair twice.',
    category: 'attack_path_analysis',
  },
  replicates_to: {
    direct: 'Replicates To',
    inverse: 'Replicates From',
    description:
      'Data replication relationship — primary database streams to replica, log shipper writes to remote, etc. Different from Sends Data To which is application-level data flow; replication is infrastructure-level state copy.',
    category: 'attack_path_analysis',
  },
  sends_data_to: {
    direct: 'Sends Data To',
    inverse: 'Receives Data From',
    description:
      'Application data flow in-transit (service → service; producer → queue). For infrastructure replication use Replicates To.',
    category: 'attack_path_analysis',
  },
  stores_data_in: {
    direct: 'Stores Data In',
    inverse: 'Stores Data For',
    description: 'Data at-rest (service/app → database/bucket/data store).',
    category: 'attack_path_analysis',
  },
  authenticates_to: {
    direct: 'Authenticates To',
    inverse: 'Authenticates',
    description: 'Authentication relationship (user/service → IdP/app/api).',
    category: 'attack_path_analysis',
  },
  granted_to: {
    direct: 'Granted To',
    inverse: 'Has Grant',
    description:
      'IAM grant — a credential/role/policy is granted TO a principal (user, service, machine identity). Use for "who is allowed to use this credential". For "what does this principal have access to" use Has Access To.',
    category: 'attack_path_analysis',
  },
  has_access_to: {
    direct: 'Has Access To',
    inverse: 'Accessed By',
    description:
      'IAM resource access — a principal/credential has been authorised to access a resource. The other half of the IAM model alongside Granted To. Use for "what can this credential reach".',
    category: 'attack_path_analysis',
  },
  load_balances: {
    direct: 'Load Balances',
    inverse: 'Load Balanced By',
    description: 'Traffic distribution (load_balancer → service/web_app).',
    category: 'attack_path_analysis',
  },
  protected_by: {
    direct: 'Protected By',
    inverse: 'Protects',
    description:
      'Active security control that can block / mitigate / quarantine (WAF, EDR with prevention, IPS, CSPM with auto-remediation, runtime security agents). Use this when the tool can modify traffic/state, not just observe it. For pure observability use Monitors.',
    category: 'control_and_observability',
  },
  monitors: {
    direct: 'Monitors',
    inverse: 'Monitored By',
    description:
      'Passive observability — telemetry collection without blocking or modifying state (SIEM ingest, APM traces, log forwarding, vulnerability scanners). For tools that can take action use Protected By.',
    category: 'control_and_observability',
  },
  manages: {
    direct: 'Manages',
    inverse: 'Managed By',
    description:
      'Control-plane management — the source asset has CRUD authority over the target (cloud account manages its resources, k8s cluster manages its workloads, IaC stack manages provisioned assets). Different from Contains which is structural hierarchy.',
    category: 'control_and_observability',
  },
}

// =============================================================================
// Constraints
// =============================================================================

export interface GeneratedRelationshipConstraint {
  sourceTypes: ExtendedAssetType[]
  targetTypes: ExtendedAssetType[]
}

export const GENERATED_RELATIONSHIP_CONSTRAINTS: Record<
  GeneratedRelationshipType,
  GeneratedRelationshipConstraint[]
> = {
  runs_on: [
    {
      sourceTypes: ['service', 'api', 'website'],
      targetTypes: ['host', 'container', 'k8s_workload', 'cloud_account'],
    },
    {
      sourceTypes: ['database'],
      targetTypes: ['host', 'container', 'cloud_account'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['k8s_cluster'],
    },
    {
      sourceTypes: ['container'],
      targetTypes: ['host', 'k8s_workload'],
    },
  ],
  deployed_to: [
    {
      sourceTypes: ['repository', 'container_image'],
      targetTypes: ['k8s_cluster', 'k8s_workload', 'cloud_account', 'host'],
    },
  ],
  contains: [
    {
      sourceTypes: ['cloud_account'],
      targetTypes: [
        'host',
        'database',
        'k8s_cluster',
        'network',
        'storage',
        'serverless',
        'load_balancer',
      ],
    },
    {
      sourceTypes: ['network'],
      targetTypes: ['host', 'cloud_account', 'load_balancer'],
    },
    {
      sourceTypes: ['host'],
      targetTypes: ['container', 'service', 'database'],
    },
    {
      sourceTypes: ['k8s_cluster'],
      targetTypes: ['k8s_workload', 'kubernetes_namespace'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['container'],
    },
    {
      sourceTypes: ['api_collection', 'api'],
      targetTypes: ['api_endpoint'],
    },
    {
      sourceTypes: ['repository'],
      targetTypes: ['container_image'],
    },
  ],
  exposes: [
    {
      sourceTypes: ['host', 'k8s_workload', 'container'],
      targetTypes: ['api_endpoint', 'service', 'api'],
    },
    {
      sourceTypes: ['domain'],
      targetTypes: ['website', 'api', 'service'],
    },
    {
      sourceTypes: ['load_balancer'],
      targetTypes: ['api', 'service', 'website'],
    },
  ],
  resolves_to: [
    {
      sourceTypes: ['domain'],
      targetTypes: ['ip_address', 'load_balancer'],
    },
  ],
  cname_of: [
    {
      sourceTypes: ['domain'],
      targetTypes: ['domain'],
    },
  ],
  depends_on: [
    {
      sourceTypes: ['service', 'api', 'website'],
      targetTypes: ['database', 'api', 'service', 'credential'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['container_image', 'database', 'api', 'service'],
    },
    {
      sourceTypes: ['mobile'],
      targetTypes: ['api', 'service'],
    },
  ],
  peer_of: [
    {
      sourceTypes: ['service', 'api'],
      targetTypes: ['service', 'api'],
    },
    {
      sourceTypes: ['database'],
      targetTypes: ['database'],
    },
    {
      sourceTypes: ['host', 'container'],
      targetTypes: ['host', 'container'],
    },
  ],
  replicates_to: [
    {
      sourceTypes: ['database', 'storage'],
      targetTypes: ['database', 'storage'],
    },
  ],
  sends_data_to: [
    {
      sourceTypes: ['service', 'api', 'website', 'mobile'],
      targetTypes: ['database', 'api', 'service', 'cloud_account'],
    },
  ],
  stores_data_in: [
    {
      sourceTypes: ['service', 'api', 'website'],
      targetTypes: ['database', 'storage', 'cloud_account'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['database', 'storage'],
    },
  ],
  authenticates_to: [
    {
      sourceTypes: ['api', 'service', 'website', 'mobile'],
      targetTypes: ['identity_provider', 'service', 'api'],
    },
    {
      sourceTypes: ['k8s_workload'],
      targetTypes: ['identity_provider', 'service'],
    },
  ],
  granted_to: [
    {
      sourceTypes: ['credential'],
      targetTypes: ['iam_user', 'iam_role', 'service_account', 'service'],
    },
  ],
  has_access_to: [
    {
      sourceTypes: ['credential', 'iam_user', 'iam_role', 'service_account', 'service'],
      targetTypes: ['cloud_account', 'database', 'api', 'service', 'k8s_cluster', 'storage'],
    },
  ],
  load_balances: [
    {
      sourceTypes: ['load_balancer', 'service', 'cloud_account'],
      targetTypes: ['host', 'k8s_workload', 'service', 'container'],
    },
  ],
  protected_by: [
    {
      sourceTypes: ['website', 'api', 'service'],
      targetTypes: ['load_balancer', 'service'],
    },
    {
      sourceTypes: ['host', 'compute'],
      targetTypes: ['service'],
    },
    {
      sourceTypes: ['cloud_account'],
      targetTypes: ['service'],
    },
  ],
  monitors: [
    {
      sourceTypes: ['service'],
      targetTypes: [
        'host',
        'k8s_cluster',
        'cloud_account',
        'api',
        'service',
        'database',
        'network',
      ],
    },
  ],
  manages: [
    {
      sourceTypes: ['cloud_account'],
      targetTypes: ['host', 'database', 'k8s_cluster', 'network', 'load_balancer'],
    },
    {
      sourceTypes: ['k8s_cluster'],
      targetTypes: ['k8s_workload', 'container'],
    },
  ],
}

// =============================================================================
// Categories (display order)
// =============================================================================

export interface GeneratedRelationshipCategory {
  id: string
  name: string
}

export const GENERATED_RELATIONSHIP_CATEGORIES: GeneratedRelationshipCategory[] = [
  { id: 'attack_surface_mapping', name: 'Attack Surface Mapping' },
  { id: 'attack_path_analysis', name: 'Attack Path Analysis' },
  { id: 'control_and_observability', name: 'Control & Observability' },
]

// =============================================================================
// Convenience: ordered ID list
// =============================================================================

export const ALL_GENERATED_RELATIONSHIP_TYPES: GeneratedRelationshipType[] = [
  'runs_on',
  'deployed_to',
  'contains',
  'exposes',
  'resolves_to',
  'cname_of',
  'depends_on',
  'peer_of',
  'replicates_to',
  'sends_data_to',
  'stores_data_in',
  'authenticates_to',
  'granted_to',
  'has_access_to',
  'load_balances',
  'protected_by',
  'monitors',
  'manages',
]
