/**
 * API Assets Mock Data
 */

import type { Api, ApiEndpoint } from "../../types";
import { daysAgo } from "./helpers";

export const apiAssets: Api[] = [
  {
    id: "api-001",
    name: "Core Banking API",
    description: "Core banking services API for account management and transactions",
    type: "rest",
    baseUrl: "https://api.vinbank.vn/v2",
    version: "2.5.0",
    authType: "oauth2",
    status: "active",
    endpointCount: 45,
    documentationUrl: "https://docs.vinbank.vn/api",
    openApiSpec: true,
    owner: "Banking Team",
    team: "Core Banking",
    riskScore: 78,
    findingCount: 6,
    requestsPerDay: 1500000,
    avgResponseTime: 85,
    errorRate: 0.02,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 1000,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-002",
    name: "Payment Gateway",
    description: "Payment processing and merchant services API",
    type: "rest",
    baseUrl: "https://payments.vinbank.vn/api/v1",
    version: "1.8.2",
    authType: "jwt",
    status: "active",
    endpointCount: 28,
    documentationUrl: "https://docs.vinbank.vn/payments",
    openApiSpec: true,
    owner: "Payment Team",
    team: "Payments",
    riskScore: 85,
    findingCount: 8,
    requestsPerDay: 800000,
    avgResponseTime: 120,
    errorRate: 0.01,
    tlsVersion: "TLS 1.3",
    corsEnabled: false,
    rateLimitEnabled: true,
    rateLimit: 500,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-003",
    name: "User Management GraphQL",
    description: "GraphQL API for user profile and authentication",
    type: "graphql",
    baseUrl: "https://api.vingroup.vn/graphql",
    version: "3.0.0",
    authType: "jwt",
    status: "active",
    endpointCount: 1,
    documentationUrl: "https://docs.vingroup.vn/graphql",
    openApiSpec: false,
    owner: "Platform Team",
    team: "Identity",
    riskScore: 62,
    findingCount: 4,
    requestsPerDay: 500000,
    avgResponseTime: 95,
    errorRate: 0.03,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 2000,
    createdAt: daysAgo(300),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-004",
    name: "Real-time Notifications",
    description: "WebSocket API for push notifications and live updates",
    type: "websocket",
    baseUrl: "wss://ws.vingroup.vn",
    version: "1.2.0",
    authType: "jwt",
    status: "active",
    endpointCount: 5,
    openApiSpec: false,
    owner: "Platform Team",
    team: "Notifications",
    riskScore: 45,
    findingCount: 2,
    requestsPerDay: 2000000,
    avgResponseTime: 15,
    errorRate: 0.005,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: false,
    createdAt: daysAgo(200),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-005",
    name: "E-commerce API",
    description: "Product catalog, cart, and order management",
    type: "rest",
    baseUrl: "https://api.vinmart.vn/v3",
    version: "3.2.1",
    authType: "api_key",
    status: "active",
    endpointCount: 67,
    documentationUrl: "https://developer.vinmart.vn",
    openApiSpec: true,
    owner: "E-commerce Team",
    team: "VinMart",
    riskScore: 52,
    findingCount: 3,
    requestsPerDay: 1200000,
    avgResponseTime: 75,
    errorRate: 0.025,
    tlsVersion: "TLS 1.2",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 3000,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-006",
    name: "Analytics gRPC Service",
    description: "High-performance analytics data streaming",
    type: "grpc",
    baseUrl: "grpc://analytics.vingroup.vn:443",
    version: "2.0.0",
    authType: "mtls",
    status: "active",
    endpointCount: 12,
    openApiSpec: false,
    owner: "Data Team",
    team: "Analytics",
    riskScore: 35,
    findingCount: 1,
    requestsPerDay: 5000000,
    avgResponseTime: 25,
    errorRate: 0.001,
    tlsVersion: "TLS 1.3",
    corsEnabled: false,
    rateLimitEnabled: false,
    createdAt: daysAgo(180),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-007",
    name: "Legacy SOAP Service",
    description: "Legacy enterprise integration services",
    type: "soap",
    baseUrl: "https://legacy.vingroup.vn/ws",
    version: "1.0.0",
    authType: "basic",
    status: "deprecated",
    endpointCount: 8,
    documentationUrl: "https://wiki.vingroup.vn/legacy-api",
    openApiSpec: false,
    owner: "IT Operations",
    team: "Legacy Systems",
    riskScore: 72,
    findingCount: 5,
    requestsPerDay: 50000,
    avgResponseTime: 350,
    errorRate: 0.08,
    tlsVersion: "TLS 1.2",
    corsEnabled: false,
    rateLimitEnabled: false,
    createdAt: daysAgo(1000),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(1),
  },
  {
    id: "api-008",
    name: "Mobile Backend API",
    description: "Backend for mobile applications",
    type: "rest",
    baseUrl: "https://mobile-api.vingroup.vn/v2",
    version: "2.1.0",
    authType: "oauth2",
    status: "active",
    endpointCount: 38,
    documentationUrl: "https://docs.vingroup.vn/mobile-api",
    openApiSpec: true,
    owner: "Mobile Team",
    team: "Mobile",
    riskScore: 58,
    findingCount: 3,
    requestsPerDay: 900000,
    avgResponseTime: 65,
    errorRate: 0.015,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 1500,
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-009",
    name: "Partner Integration API",
    description: "External partner and B2B integration services",
    type: "rest",
    baseUrl: "https://partner-api.vingroup.vn/v1",
    version: "1.5.0",
    authType: "oauth2",
    status: "active",
    endpointCount: 22,
    documentationUrl: "https://partner.vingroup.vn/docs",
    openApiSpec: true,
    owner: "Partnership Team",
    team: "B2B",
    riskScore: 48,
    findingCount: 2,
    requestsPerDay: 150000,
    avgResponseTime: 110,
    errorRate: 0.02,
    tlsVersion: "TLS 1.3",
    corsEnabled: false,
    rateLimitEnabled: true,
    rateLimit: 200,
    createdAt: daysAgo(150),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-010",
    name: "Internal Admin API",
    description: "Internal administration and management API",
    type: "rest",
    baseUrl: "https://admin-api.internal.vn/v1",
    version: "1.0.5",
    authType: "jwt",
    status: "development",
    endpointCount: 15,
    openApiSpec: true,
    owner: "Platform Team",
    team: "Internal Tools",
    riskScore: 42,
    findingCount: 1,
    requestsPerDay: 10000,
    avgResponseTime: 55,
    errorRate: 0.04,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: false,
    createdAt: daysAgo(60),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
];

export const apiEndpoints: ApiEndpoint[] = [
  // Core Banking API endpoints
  {
    id: "endpoint-001",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/accounts",
    method: "GET",
    description: "List all user accounts",
    parameters: [
      { name: "page", in: "query", required: false, type: "integer" },
      { name: "limit", in: "query", required: false, type: "integer" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 45,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 65,
    errorRate: 0.01,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-002",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/accounts/{accountId}",
    method: "GET",
    description: "Get account details",
    parameters: [
      { name: "accountId", in: "path", required: true, type: "string" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 55,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 45,
    errorRate: 0.005,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-003",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/transfers",
    method: "POST",
    description: "Create a new transfer",
    parameters: [
      { name: "body", in: "body", required: true, type: "TransferRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 85,
    findingCount: 2,
    lastCalled: daysAgo(0),
    avgResponseTime: 120,
    errorRate: 0.02,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-004",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/transactions",
    method: "GET",
    description: "List transaction history",
    parameters: [
      { name: "accountId", in: "query", required: true, type: "string" },
      { name: "from", in: "query", required: false, type: "date" },
      { name: "to", in: "query", required: false, type: "date" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 65,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 95,
    errorRate: 0.015,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  // Payment Gateway endpoints
  {
    id: "endpoint-005",
    apiId: "api-002",
    apiName: "Payment Gateway",
    path: "/payments/initiate",
    method: "POST",
    description: "Initiate a payment transaction",
    parameters: [
      { name: "body", in: "body", required: true, type: "PaymentRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 92,
    findingCount: 3,
    lastCalled: daysAgo(0),
    avgResponseTime: 150,
    errorRate: 0.008,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-006",
    apiId: "api-002",
    apiName: "Payment Gateway",
    path: "/payments/{paymentId}/status",
    method: "GET",
    description: "Get payment status",
    parameters: [
      { name: "paymentId", in: "path", required: true, type: "string" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 45,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 35,
    errorRate: 0.005,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-007",
    apiId: "api-002",
    apiName: "Payment Gateway",
    path: "/refunds",
    method: "POST",
    description: "Process refund request",
    parameters: [
      { name: "body", in: "body", required: true, type: "RefundRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 88,
    findingCount: 2,
    lastCalled: daysAgo(0),
    avgResponseTime: 180,
    errorRate: 0.012,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
  },
  // E-commerce API endpoints
  {
    id: "endpoint-008",
    apiId: "api-005",
    apiName: "E-commerce API",
    path: "/products",
    method: "GET",
    description: "List products",
    parameters: [
      { name: "category", in: "query", required: false, type: "string" },
      { name: "page", in: "query", required: false, type: "integer" },
    ],
    responseType: "application/json",
    authenticated: false,
    deprecated: false,
    riskScore: 25,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 55,
    errorRate: 0.02,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-009",
    apiId: "api-005",
    apiName: "E-commerce API",
    path: "/cart",
    method: "POST",
    description: "Add item to cart",
    parameters: [
      { name: "body", in: "body", required: true, type: "CartItem" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 42,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 45,
    errorRate: 0.018,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-010",
    apiId: "api-005",
    apiName: "E-commerce API",
    path: "/orders",
    method: "POST",
    description: "Create new order",
    parameters: [
      { name: "body", in: "body", required: true, type: "OrderRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 68,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 120,
    errorRate: 0.025,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
  },
  // Mobile Backend API endpoints
  {
    id: "endpoint-011",
    apiId: "api-008",
    apiName: "Mobile Backend API",
    path: "/auth/login",
    method: "POST",
    description: "User login",
    parameters: [
      { name: "body", in: "body", required: true, type: "LoginRequest" },
    ],
    responseType: "application/json",
    authenticated: false,
    deprecated: false,
    riskScore: 75,
    findingCount: 2,
    lastCalled: daysAgo(0),
    avgResponseTime: 85,
    errorRate: 0.03,
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-012",
    apiId: "api-008",
    apiName: "Mobile Backend API",
    path: "/auth/refresh",
    method: "POST",
    description: "Refresh access token",
    parameters: [
      { name: "Authorization", in: "header", required: true, type: "string" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 55,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 35,
    errorRate: 0.01,
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
  },
  // Legacy SOAP Service (deprecated endpoints)
  {
    id: "endpoint-013",
    apiId: "api-007",
    apiName: "Legacy SOAP Service",
    path: "/CustomerService",
    method: "POST",
    description: "Legacy customer service SOAP endpoint",
    responseType: "text/xml",
    authenticated: true,
    deprecated: true,
    riskScore: 82,
    findingCount: 3,
    lastCalled: daysAgo(1),
    avgResponseTime: 450,
    errorRate: 0.1,
    createdAt: daysAgo(1000),
    lastSeen: daysAgo(1),
  },
  {
    id: "endpoint-014",
    apiId: "api-007",
    apiName: "Legacy SOAP Service",
    path: "/OrderService",
    method: "POST",
    description: "Legacy order service SOAP endpoint",
    responseType: "text/xml",
    authenticated: true,
    deprecated: true,
    riskScore: 78,
    findingCount: 2,
    lastCalled: daysAgo(2),
    avgResponseTime: 380,
    errorRate: 0.08,
    createdAt: daysAgo(1000),
    lastSeen: daysAgo(2),
  },
];
