/**
 * Cloud Assets Mock Data
 */

import type { BaseAsset } from './helpers'
import { daysAgo } from './helpers'

export const cloudAssets: BaseAsset[] = [
  {
    id: 'cloud-001',
    type: 'cloud_account',
    name: 'aws-prod-vpc-main',
    description: 'Production VPC on AWS',
    status: 'active',
    riskScore: 55,
    findingCount: 3,
    groupId: 'grp-006',
    groupName: 'Cloud Infrastructure',
    metadata: {
      cloudProvider: 'aws',
      region: 'ap-southeast-1',
      resourceType: 'VPC',
    },
    tags: ['production', 'network'],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: 'cloud-002',
    type: 'cloud_account',
    name: 'gcp-prod-gke-cluster',
    description: 'Production Kubernetes Cluster',
    status: 'active',
    riskScore: 72,
    findingCount: 5,
    groupId: 'grp-006',
    groupName: 'Cloud Infrastructure',
    metadata: {
      cloudProvider: 'gcp',
      region: 'asia-southeast1',
      resourceType: 'GKE Cluster',
    },
    tags: ['critical', 'kubernetes'],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(0),
  },
  {
    id: 'cloud-003',
    type: 'cloud_account',
    name: 'azure-prod-sql-server',
    description: 'Azure SQL Database Server',
    status: 'active',
    riskScore: 68,
    findingCount: 4,
    groupId: 'grp-006',
    groupName: 'Cloud Infrastructure',
    metadata: {
      cloudProvider: 'azure',
      region: 'Southeast Asia',
      resourceType: 'SQL Server',
    },
    tags: ['critical', 'database'],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: 'cloud-004',
    type: 'cloud_account',
    name: 'aws-prod-s3-assets',
    description: 'Production Assets Storage',
    status: 'active',
    riskScore: 42,
    findingCount: 2,
    groupId: 'grp-002',
    groupName: 'Production - E-commerce',
    metadata: {
      cloudProvider: 'aws',
      region: 'ap-southeast-1',
      resourceType: 'S3 Bucket',
    },
    tags: ['production', 'storage'],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(3),
  },
  {
    id: 'cloud-005',
    type: 'cloud_account',
    name: 'aws-staging-ec2-fleet',
    description: 'Staging EC2 Instances',
    status: 'active',
    riskScore: 28,
    findingCount: 1,
    groupId: 'grp-004',
    groupName: 'Staging Environment',
    metadata: {
      cloudProvider: 'aws',
      region: 'ap-southeast-1',
      resourceType: 'EC2',
    },
    tags: ['staging', 'compute'],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(1),
  },
]
