/**
 * Container Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const containerAssets: BaseAsset[] = [
  {
    id: "container-001",
    type: "container",
    name: "api-gateway",
    description: "API Gateway service",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      image: "nginx",
      imageTag: "1.25-alpine",
      registry: "docker.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "production",
      cluster: "prod-gke-cluster",
      replicas: 3,
      cpuLimit: "500m",
      memoryLimit: "512Mi",
      containerPorts: [80, 443],
      vulnerabilities: 2,
    },
    tags: ["production", "gateway", "nginx"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "container-002",
    type: "container",
    name: "user-service",
    description: "User microservice",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      image: "vingroup/user-service",
      imageTag: "v2.5.1",
      registry: "gcr.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "production",
      cluster: "prod-gke-cluster",
      replicas: 5,
      cpuLimit: "1000m",
      memoryLimit: "1Gi",
      containerPorts: [8080],
      vulnerabilities: 5,
    },
    tags: ["production", "microservice", "java"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(0),
  },
  {
    id: "container-003",
    type: "container",
    name: "payment-processor",
    description: "Payment processing service",
    status: "active",
    riskScore: 78,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      image: "vingroup/payment-processor",
      imageTag: "v3.1.0",
      registry: "gcr.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "production",
      cluster: "prod-gke-cluster",
      replicas: 3,
      cpuLimit: "2000m",
      memoryLimit: "2Gi",
      containerPorts: [8443],
      vulnerabilities: 8,
    },
    tags: ["critical", "payment", "pci-dss"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "container-004",
    type: "container",
    name: "redis-cache",
    description: "Redis caching layer",
    status: "active",
    riskScore: 32,
    findingCount: 1,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      image: "redis",
      imageTag: "7.2-alpine",
      registry: "docker.io",
      runtime: "docker",
      orchestrator: "docker-swarm",
      namespace: "default",
      replicas: 1,
      cpuLimit: "500m",
      memoryLimit: "1Gi",
      containerPorts: [6379],
      vulnerabilities: 1,
    },
    tags: ["production", "cache", "redis"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "container-005",
    type: "container",
    name: "logging-agent",
    description: "Fluent Bit logging agent",
    status: "active",
    riskScore: 18,
    findingCount: 0,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      image: "fluent/fluent-bit",
      imageTag: "2.1.10",
      registry: "docker.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "monitoring",
      cluster: "prod-gke-cluster",
      replicas: 1,
      cpuLimit: "200m",
      memoryLimit: "256Mi",
      containerPorts: [2020, 24224],
      vulnerabilities: 0,
    },
    tags: ["monitoring", "logging"],
    firstSeen: daysAgo(100),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
];
