/**
 * Credential Leak Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const credentialAssets: BaseAsset[] = [
  {
    id: "cred-001",
    type: "credential",
    name: "admin@vingroup.vn",
    description: "Leaked admin credentials",
    status: "active",
    riskScore: 95,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Data breach - DarkWeb",
      username: "admin@vingroup.vn",
      leakDate: "2024-08-15",
      secretValue: "V1ngr0up@dmin2024!",
      credentialType: "password",
    },
    tags: ["critical", "credential-leak"],
    firstSeen: daysAgo(120),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(0),
  },
  {
    id: "cred-002",
    type: "credential",
    name: "developer@fpt.com.vn",
    description: "Developer account exposed",
    status: "active",
    riskScore: 75,
    findingCount: 1,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      source: "GitHub commit history",
      username: "developer@fpt.com.vn",
      leakDate: "2024-09-20",
    },
    tags: ["high", "credential-leak"],
    firstSeen: daysAgo(90),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: "cred-003",
    type: "credential",
    name: "api-key-techcombank",
    description: "API key leaked in public repo",
    status: "pending",
    riskScore: 88,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Public GitHub repository",
      username: "service-account",
      leakDate: "2024-10-05",
      secretValue: "tcb_live_sk_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0",
      credentialType: "api_key",
    },
    tags: ["critical", "api-key-leak"],
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: "cred-004",
    type: "credential",
    name: "db-admin@vpbank.vn",
    description: "Database admin credentials",
    status: "completed",
    riskScore: 45,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Pastebin leak",
      username: "db-admin@vpbank.vn",
      leakDate: "2024-06-10",
    },
    tags: ["resolved", "credential-leak"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(30),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: "cred-005",
    type: "credential",
    name: "ops@viettel.com.vn",
    description: "Operations team credentials",
    status: "active",
    riskScore: 65,
    findingCount: 1,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      source: "Credential stuffing attack",
      username: "ops@viettel.com.vn",
      leakDate: "2024-11-01",
    },
    tags: ["high", "credential-leak"],
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
  {
    id: "cred-006",
    type: "credential",
    name: "aws-access-key-prod",
    description: "AWS access key exposed in CI logs",
    status: "active",
    riskScore: 92,
    findingCount: 1,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      source: "CI/CD Pipeline logs",
      username: "aws-service-account",
      leakDate: "2024-11-15",
      secretValue: "AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
      credentialType: "aws_key",
    },
    tags: ["critical", "aws-key-leak"],
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0),
  },
  {
    id: "cred-007",
    type: "credential",
    name: "support@momo.vn",
    description: "Customer support credentials found in phishing database",
    status: "active",
    riskScore: 70,
    findingCount: 1,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      source: "Phishing database",
      username: "support@momo.vn",
      leakDate: "2024-10-20",
    },
    tags: ["high", "credential-leak"],
    firstSeen: daysAgo(55),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(2),
  },
  {
    id: "cred-008",
    type: "credential",
    name: "jenkins-admin",
    description: "Jenkins admin credentials in public Gist",
    status: "pending",
    riskScore: 85,
    findingCount: 1,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      source: "GitHub Gist",
      username: "jenkins-admin",
      leakDate: "2024-09-05",
    },
    tags: ["critical", "credential-leak"],
    firstSeen: daysAgo(100),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
  {
    id: "cred-009",
    type: "credential",
    name: "slack-webhook-token",
    description: "Slack webhook URL leaked in npm package",
    status: "completed",
    riskScore: 35,
    findingCount: 1,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      source: "npm package analysis",
      username: "slack-integration",
      leakDate: "2024-07-20",
    },
    tags: ["medium", "webhook-leak"],
    firstSeen: daysAgo(160),
    lastSeen: daysAgo(60),
    createdAt: daysAgo(160),
    updatedAt: daysAgo(60),
  },
  {
    id: "cred-010",
    type: "credential",
    name: "root@db-primary.internal",
    description: "Database root password in Confluence page",
    status: "active",
    riskScore: 98,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Internal documentation leak",
      username: "root",
      leakDate: "2024-11-10",
      secretValue: "Pr0d_DB_R00t_P@ssw0rd_2024!",
      credentialType: "database_cred",
    },
    tags: ["critical", "database-credential"],
    firstSeen: daysAgo(35),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(35),
    updatedAt: daysAgo(0),
  },
  {
    id: "cred-011",
    type: "credential",
    name: "stripe-api-key-live",
    description: "Stripe live API key in client-side code",
    status: "active",
    riskScore: 90,
    findingCount: 1,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      source: "Client-side JavaScript",
      username: "stripe-service",
      leakDate: "2024-10-25",
    },
    tags: ["critical", "api-key-leak", "payment"],
    firstSeen: daysAgo(50),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(1),
  },
  {
    id: "cred-012",
    type: "credential",
    name: "hr-system@company.vn",
    description: "HR system credentials in email attachment",
    status: "pending",
    riskScore: 60,
    findingCount: 1,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      source: "Email attachment scan",
      username: "hr-system@company.vn",
      leakDate: "2024-08-30",
    },
    tags: ["medium", "credential-leak"],
    firstSeen: daysAgo(110),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(110),
    updatedAt: daysAgo(10),
  },
  {
    id: "cred-013",
    type: "credential",
    name: "gitlab-deploy-token",
    description: "GitLab deploy token exposed in docker-compose",
    status: "completed",
    riskScore: 40,
    findingCount: 1,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      source: "Docker Hub public image",
      username: "gitlab-ci",
      leakDate: "2024-05-15",
    },
    tags: ["medium", "token-leak"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(90),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(90),
  },
  {
    id: "cred-014",
    type: "credential",
    name: "sysadmin@datacenter.vn",
    description: "Datacenter admin credentials in breach dump",
    status: "inactive",
    riskScore: 55,
    findingCount: 1,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      source: "Data breach compilation",
      username: "sysadmin@datacenter.vn",
      leakDate: "2024-04-10",
    },
    tags: ["medium", "credential-leak"],
    firstSeen: daysAgo(240),
    lastSeen: daysAgo(120),
    createdAt: daysAgo(240),
    updatedAt: daysAgo(120),
  },
  {
    id: "cred-015",
    type: "credential",
    name: "mongodb-atlas-key",
    description: "MongoDB Atlas connection string in env file",
    status: "active",
    riskScore: 82,
    findingCount: 1,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      source: "Public .env file",
      username: "mongodb-service",
      leakDate: "2024-11-05",
    },
    tags: ["critical", "database-credential"],
    firstSeen: daysAgo(40),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(0),
  },
];
