/**
 * Database Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const databaseAssets: BaseAsset[] = [
  {
    id: "db-001",
    type: "database",
    name: "core-banking-db",
    description: "Core banking PostgreSQL database",
    status: "active",
    riskScore: 82,
    findingCount: 6,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      engine: "postgresql",
      dbVersion: "15.4",
      dbHost: "db.core-banking.internal.vn",
      dbPort: 5432,
      sizeGB: 500,
      encryption: true,
      backupEnabled: true,
      lastBackup: daysAgo(0),
      replication: "replica-set",
      connections: 150,
    },
    tags: ["critical", "production", "banking"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(0),
  },
  {
    id: "db-002",
    type: "database",
    name: "ecommerce-mysql",
    description: "E-commerce MySQL database",
    status: "active",
    riskScore: 58,
    findingCount: 4,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      engine: "mysql",
      dbVersion: "8.0.35",
      dbHost: "db.ecommerce.internal.vn",
      dbPort: 3306,
      sizeGB: 200,
      encryption: true,
      backupEnabled: true,
      lastBackup: daysAgo(0),
      replication: "replica-set",
      connections: 80,
    },
    tags: ["production", "ecommerce"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "db-003",
    type: "database",
    name: "analytics-mongodb",
    description: "Analytics MongoDB cluster",
    status: "active",
    riskScore: 45,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      engine: "mongodb",
      dbVersion: "7.0.4",
      dbHost: "mongo.analytics.internal.vn",
      dbPort: 27017,
      sizeGB: 150,
      encryption: true,
      backupEnabled: true,
      lastBackup: daysAgo(1),
      replication: "cluster",
      connections: 45,
    },
    tags: ["production", "analytics"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "db-004",
    type: "database",
    name: "cache-redis",
    description: "Redis cache cluster",
    status: "active",
    riskScore: 28,
    findingCount: 1,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      engine: "redis",
      dbVersion: "7.2.3",
      dbHost: "redis.cache.internal.vn",
      dbPort: 6379,
      sizeGB: 16,
      encryption: false,
      backupEnabled: false,
      replication: "cluster",
      connections: 200,
    },
    tags: ["production", "cache"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(3),
  },
  {
    id: "db-005",
    type: "database",
    name: "staging-postgresql",
    description: "Staging PostgreSQL database",
    status: "active",
    riskScore: 35,
    findingCount: 2,
    groupId: "grp-004",
    groupName: "Staging Environment",
    metadata: {
      engine: "postgresql",
      dbVersion: "15.4",
      dbHost: "db.staging.internal.vn",
      dbPort: 5432,
      sizeGB: 50,
      encryption: false,
      backupEnabled: true,
      lastBackup: daysAgo(1),
      replication: "single",
      connections: 20,
    },
    tags: ["staging", "testing"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
];
