/**
 * Domain Assets Mock Data
 *
 * Includes root domains and their subdomains for tree view demonstration
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const domainAssets: BaseAsset[] = [
  // ============================================
  // vnsecurity.io - Root domain with subdomains
  // ============================================
  {
    id: "dom-001",
    type: "domain",
    name: "vnsecurity.io",
    description: "Main corporate domain for VNSecurity",
    status: "active",
    riskScore: 45,
    findingCount: 2,
    groupId: "grp-001",
    groupName: "Production - Core",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-05-15",
      nameservers: ["ns1.vnsecurity.io", "ns2.vnsecurity.io"],
      rootDomain: "vnsecurity.io",
      domainLevel: 0,
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(365),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-001-sub-1",
    type: "domain",
    name: "scanner.vnsecurity.io",
    description: "Internal security scanner service",
    status: "active",
    riskScore: 0,
    findingCount: 0,
    groupId: "grp-001",
    groupName: "Production - Core",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "vnsecurity.io",
      parentDomain: "vnsecurity.io",
      domainLevel: 1,
    },
    tags: ["internal", "scanner"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-001-sub-2",
    type: "domain",
    name: "staging.vnsecurity.io",
    description: "Staging environment",
    status: "active",
    riskScore: 20,
    findingCount: 0,
    groupId: "grp-002",
    groupName: "Staging",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "vnsecurity.io",
      parentDomain: "vnsecurity.io",
      domainLevel: 1,
    },
    tags: ["staging", "internal"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-001-sub-3",
    type: "domain",
    name: "portal.vnsecurity.io",
    description: "Customer portal",
    status: "active",
    riskScore: 35,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "vnsecurity.io",
      parentDomain: "vnsecurity.io",
      domainLevel: 1,
    },
    tags: ["production", "customer-facing"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-001-sub-4",
    type: "domain",
    name: "api.vnsecurity.io",
    description: "Public API endpoint",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-001",
    groupName: "Production - Core",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "vnsecurity.io",
      parentDomain: "vnsecurity.io",
      domainLevel: 1,
    },
    tags: ["production", "api", "external"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(0),
  },

  // ============================================
  // techviet.vn - Root domain with subdomains
  // ============================================
  {
    id: "dom-002",
    type: "domain",
    name: "techviet.vn",
    description: "TechViet main corporate domain",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-003",
    groupName: "Production - TechViet",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-08-20",
      nameservers: ["ns1.techviet.vn", "ns2.techviet.vn"],
      rootDomain: "techviet.vn",
      domainLevel: 0,
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(2),
  },
  {
    id: "dom-002-sub-1",
    type: "domain",
    name: "www.techviet.vn",
    description: "Main website",
    status: "active",
    riskScore: 65,
    findingCount: 2,
    groupId: "grp-003",
    groupName: "Production - TechViet",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "techviet.vn",
      parentDomain: "techviet.vn",
      domainLevel: 1,
    },
    tags: ["production", "website"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-002-sub-2",
    type: "domain",
    name: "mail.techviet.vn",
    description: "Email server",
    status: "active",
    riskScore: 40,
    findingCount: 1,
    groupId: "grp-003",
    groupName: "Production - TechViet",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "techviet.vn",
      parentDomain: "techviet.vn",
      domainLevel: 1,
    },
    tags: ["production", "email"],
    firstSeen: daysAgo(380),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(380),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-002-sub-3",
    type: "domain",
    name: "shop.techviet.vn",
    description: "E-commerce platform",
    status: "active",
    riskScore: 82,
    findingCount: 4,
    groupId: "grp-003",
    groupName: "Production - TechViet",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "techviet.vn",
      parentDomain: "techviet.vn",
      domainLevel: 1,
    },
    tags: ["production", "ecommerce", "critical"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(0),
  },

  // ============================================
  // example.com.vn - Root domain with deep hierarchy
  // ============================================
  {
    id: "dom-003",
    type: "domain",
    name: "example.com.vn",
    description: "Example Corp Vietnam",
    status: "active",
    riskScore: 58,
    findingCount: 3,
    groupId: "grp-004",
    groupName: "Production - Example",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2025-12-31",
      nameservers: ["ns1.example.com.vn", "ns2.example.com.vn"],
      rootDomain: "example.com.vn",
      domainLevel: 0,
    },
    tags: ["production"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(3),
  },
  {
    id: "dom-003-sub-1",
    type: "domain",
    name: "api.example.com.vn",
    description: "API gateway",
    status: "active",
    riskScore: 45,
    findingCount: 1,
    groupId: "grp-004",
    groupName: "Production - Example",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "example.com.vn",
      parentDomain: "example.com.vn",
      domainLevel: 1,
    },
    tags: ["production", "api"],
    firstSeen: daysAgo(450),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(450),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-003-sub-2",
    type: "domain",
    name: "v2.api.example.com.vn",
    description: "API v2 (new version)",
    status: "active",
    riskScore: 30,
    findingCount: 0,
    groupId: "grp-004",
    groupName: "Production - Example",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "example.com.vn",
      parentDomain: "api.example.com.vn",
      domainLevel: 2,
    },
    tags: ["production", "api", "v2"],
    firstSeen: daysAgo(100),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-003-sub-3",
    type: "domain",
    name: "dev.example.com.vn",
    description: "Development environment",
    status: "inactive",
    riskScore: 15,
    findingCount: 0,
    groupId: "grp-005",
    groupName: "Development",
    metadata: {
      registrar: "-",
      expiryDate: "-",
      rootDomain: "example.com.vn",
      parentDomain: "example.com.vn",
      domainLevel: 1,
    },
    tags: ["development", "internal"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(30),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },

  // ============================================
  // standalone.io - Single domain (no subdomains)
  // ============================================
  {
    id: "dom-004",
    type: "domain",
    name: "standalone.io",
    description: "Standalone service domain",
    status: "active",
    riskScore: 25,
    findingCount: 1,
    groupId: "grp-006",
    groupName: "External Services",
    metadata: {
      registrar: "GoDaddy",
      expiryDate: "2027-01-15",
      nameservers: ["ns1.godaddy.com", "ns2.godaddy.com"],
      rootDomain: "standalone.io",
      domainLevel: 0,
    },
    tags: ["external"],
    firstSeen: daysAgo(120),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
  },
];
