/**
 * Asset Findings Mock Data
 */

import type { AssetFinding } from '../../types'
import { daysAgo } from './helpers'

// API Findings
const apiFindings: AssetFinding[] = [
  {
    id: 'finding-api-001',
    type: 'vulnerability',
    severity: 'critical',
    status: 'open',
    title: 'SQL Injection in transfer endpoint',
    description:
      'The /transfers endpoint is vulnerable to SQL injection via the accountId parameter.',
    assetId: 'api-001',
    assetName: 'Core Banking API',
    assetType: 'api',
    cveId: 'CVE-2024-5678',
    cvssScore: 9.8,
    cweId: 'CWE-89',
    remediation: 'Use parameterized queries and input validation.',
    references: ['https://owasp.org/www-community/attacks/SQL_Injection'],
    firstSeen: daysAgo(5),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-api-002',
    type: 'misconfiguration',
    severity: 'high',
    status: 'open',
    title: 'Missing rate limiting on payment endpoint',
    description:
      'The /payments/initiate endpoint lacks proper rate limiting, allowing potential abuse.',
    assetId: 'api-002',
    assetName: 'Payment Gateway',
    assetType: 'api',
    rule: 'API-SEC-001',
    remediation: 'Implement rate limiting with appropriate thresholds.',
    firstSeen: daysAgo(14),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-api-003',
    type: 'misconfiguration',
    severity: 'high',
    status: 'in_progress',
    title: 'Excessive data exposure in response',
    description: 'API responses include sensitive data fields that should be filtered.',
    assetId: 'api-002',
    assetName: 'Payment Gateway',
    assetType: 'api',
    rule: 'API-SEC-003',
    remediation: 'Implement response filtering to remove sensitive data.',
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-api-004',
    type: 'vulnerability',
    severity: 'medium',
    status: 'open',
    title: 'Broken authentication in refresh token',
    description: "Refresh tokens don't expire properly, allowing indefinite session extension.",
    assetId: 'api-008',
    assetName: 'Mobile Backend API',
    assetType: 'api',
    cweId: 'CWE-613',
    remediation: 'Implement proper token rotation and expiration.',
    firstSeen: daysAgo(21),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-api-005',
    type: 'misconfiguration',
    severity: 'critical',
    status: 'open',
    title: 'No authentication on SOAP endpoint',
    description: 'Legacy SOAP endpoint accepts requests without proper authentication.',
    assetId: 'api-007',
    assetName: 'Legacy SOAP Service',
    assetType: 'api',
    rule: 'API-AUTH-001',
    remediation: 'Implement WS-Security or migrate to modern REST API with OAuth.',
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
  },
]

// Domain findings
const domainFindings: AssetFinding[] = [
  {
    id: 'finding-001',
    type: 'misconfiguration',
    severity: 'high',
    status: 'open',
    title: 'Missing DNSSEC configuration',
    description:
      'DNSSEC is not enabled for this domain, making it vulnerable to DNS spoofing attacks.',
    assetId: 'dom-001',
    assetName: 'vingroup.vn',
    assetType: 'domain',
    rule: 'DNS-001',
    remediation: 'Enable DNSSEC at your domain registrar and configure DS records.',
    references: ['https://www.cloudflare.com/dns/dnssec/'],
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-002',
    type: 'misconfiguration',
    severity: 'medium',
    status: 'open',
    title: 'SPF record too permissive',
    description:
      'The SPF record uses +all which allows any server to send emails on behalf of the domain.',
    assetId: 'dom-001',
    assetName: 'vingroup.vn',
    assetType: 'domain',
    rule: 'EMAIL-002',
    remediation: 'Update SPF record to use -all or ~all to restrict email sending.',
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
  },
]

// Website findings
const websiteFindings: AssetFinding[] = [
  {
    id: 'finding-003',
    type: 'vulnerability',
    severity: 'critical',
    status: 'open',
    title: 'SQL Injection vulnerability',
    description:
      'The login endpoint is vulnerable to SQL injection attacks via the username parameter.',
    assetId: 'web-002',
    assetName: 'ebanking.techcombank.com.vn',
    assetType: 'website',
    cveId: 'CVE-2024-1234',
    cvssScore: 9.8,
    cweId: 'CWE-89',
    remediation: 'Use parameterized queries instead of string concatenation for SQL queries.',
    references: ['https://owasp.org/www-community/attacks/SQL_Injection'],
    firstSeen: daysAgo(7),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-004',
    type: 'misconfiguration',
    severity: 'high',
    status: 'in_progress',
    title: 'Missing security headers',
    description:
      'The application is missing critical security headers: X-Frame-Options, Content-Security-Policy.',
    assetId: 'web-002',
    assetName: 'ebanking.techcombank.com.vn',
    assetType: 'website',
    rule: 'HEADER-001',
    remediation: 'Add X-Frame-Options: DENY and implement a strict Content-Security-Policy.',
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
  },
]

// Host findings
const hostFindings: AssetFinding[] = [
  {
    id: 'finding-005',
    type: 'vulnerability',
    severity: 'critical',
    status: 'open',
    title: 'OpenSSH Remote Code Execution',
    description: 'The installed OpenSSH version is vulnerable to remote code execution.',
    assetId: 'host-001',
    assetName: 'prod-web-01',
    assetType: 'host',
    cveId: 'CVE-2024-6387',
    cvssScore: 8.1,
    cweId: 'CWE-362',
    remediation: 'Upgrade OpenSSH to version 9.8 or later.',
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-6387'],
    firstSeen: daysAgo(14),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-006',
    type: 'misconfiguration',
    severity: 'medium',
    status: 'open',
    title: 'Root login enabled via SSH',
    description: 'SSH is configured to allow direct root login, increasing attack surface.',
    assetId: 'host-001',
    assetName: 'prod-web-01',
    assetType: 'host',
    rule: 'SSH-002',
    benchmark: 'CIS Ubuntu 22.04',
    remediation: "Set PermitRootLogin to 'no' in /etc/ssh/sshd_config.",
    firstSeen: daysAgo(90),
    lastSeen: daysAgo(0),
  },
]

// Container/K8s findings
const containerFindings: AssetFinding[] = [
  {
    id: 'finding-007',
    type: 'misconfiguration',
    severity: 'high',
    status: 'open',
    title: 'Container running as root',
    description:
      'The container is running with root privileges, violating the principle of least privilege.',
    assetId: 'container-003',
    assetName: 'payment-processor',
    assetType: 'container',
    rule: 'K8S-SEC-001',
    benchmark: 'CIS Kubernetes',
    remediation: 'Set securityContext.runAsNonRoot: true in the pod spec.',
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-008',
    type: 'vulnerability',
    severity: 'critical',
    status: 'open',
    title: 'Critical CVE in base image',
    description: 'The container image contains a critical vulnerability in the OpenSSL library.',
    assetId: 'container-003',
    assetName: 'payment-processor',
    assetType: 'container',
    cveId: 'CVE-2024-0567',
    cvssScore: 9.1,
    cweId: 'CWE-119',
    remediation: 'Rebuild the image with an updated base image that patches OpenSSL.',
    firstSeen: daysAgo(5),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-009',
    type: 'misconfiguration',
    severity: 'medium',
    status: 'open',
    title: 'No resource limits defined',
    description: 'The container has no CPU/memory limits, risking resource exhaustion.',
    assetId: 'container-002',
    assetName: 'user-service',
    assetType: 'container',
    rule: 'K8S-RES-001',
    remediation: 'Define resources.limits in the container spec.',
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
  },
]

// Database findings
const databaseFindings: AssetFinding[] = [
  {
    id: 'finding-010',
    type: 'misconfiguration',
    severity: 'critical',
    status: 'open',
    title: 'Database exposed to internet',
    description: 'The database port 5432 is accessible from the public internet.',
    assetId: 'db-001',
    assetName: 'core-banking-db',
    assetType: 'database',
    rule: 'DB-NET-001',
    remediation: 'Configure firewall rules to restrict database access to trusted IPs only.',
    firstSeen: daysAgo(3),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-011',
    type: 'misconfiguration',
    severity: 'high',
    status: 'open',
    title: 'Weak password policy',
    description: 'Database password policy does not enforce complexity requirements.',
    assetId: 'db-001',
    assetName: 'core-banking-db',
    assetType: 'database',
    rule: 'DB-AUTH-002',
    benchmark: 'CIS PostgreSQL',
    remediation: 'Configure password_encryption and set minimum password length.',
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
  },
]

// Mobile app findings
const mobileFindings: AssetFinding[] = [
  {
    id: 'finding-012',
    type: 'vulnerability',
    severity: 'high',
    status: 'open',
    title: 'Insecure data storage',
    description: 'Sensitive data is stored in SharedPreferences without encryption.',
    assetId: 'mobile-001',
    assetName: 'VinBank Mobile',
    assetType: 'mobile',
    cweId: 'CWE-312',
    remediation: 'Use EncryptedSharedPreferences or Android Keystore for sensitive data.',
    references: ['https://owasp.org/www-project-mobile-top-10/'],
    firstSeen: daysAgo(21),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-013',
    type: 'misconfiguration',
    severity: 'medium',
    status: 'open',
    title: 'Debug mode enabled in release build',
    description: 'The application has debuggable flag set to true in the release APK.',
    assetId: 'mobile-001',
    assetName: 'VinBank Mobile',
    assetType: 'mobile',
    rule: 'MOBILE-001',
    remediation: "Set android:debuggable='false' in AndroidManifest.xml for release builds.",
    firstSeen: daysAgo(14),
    lastSeen: daysAgo(0),
  },
]

// Repository findings
const repositoryFindings: AssetFinding[] = [
  {
    id: 'finding-014',
    type: 'secret',
    severity: 'critical',
    status: 'open',
    title: 'AWS credentials in source code',
    description: 'Hardcoded AWS access key found in configuration file.',
    assetId: 'proj-003',
    assetName: 'viettel/infrastructure-terraform',
    assetType: 'repository',
    rule: 'SECRET-001',
    remediation: 'Remove the credentials and rotate the exposed keys immediately.',
    firstSeen: daysAgo(2),
    lastSeen: daysAgo(0),
  },
  {
    id: 'finding-015',
    type: 'vulnerability',
    severity: 'high',
    status: 'in_progress',
    title: 'Vulnerable dependency: log4j',
    description: 'The project uses log4j 2.14.0 which is vulnerable to Log4Shell.',
    assetId: 'proj-001',
    assetName: 'vingroup/core-banking-api',
    assetType: 'repository',
    cveId: 'CVE-2021-44228',
    cvssScore: 10.0,
    cweId: 'CWE-502',
    remediation: 'Upgrade log4j to version 2.17.1 or later.',
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
]

// Cloud findings
const cloudFindings: AssetFinding[] = [
  {
    id: 'finding-016',
    type: 'misconfiguration',
    severity: 'high',
    status: 'open',
    title: 'S3 bucket public access enabled',
    description: 'The S3 bucket has public access enabled, exposing files to the internet.',
    assetId: 'cloud-004',
    assetName: 'aws-prod-s3-assets',
    assetType: 'cloud_account',
    rule: 'AWS-S3-001',
    benchmark: 'CIS AWS',
    remediation: 'Enable S3 Block Public Access settings at the bucket level.',
    firstSeen: daysAgo(7),
    lastSeen: daysAgo(0),
  },
]

// Service findings
const serviceFindings: AssetFinding[] = [
  {
    id: 'finding-017',
    type: 'misconfiguration',
    severity: 'high',
    status: 'open',
    title: 'Redis without authentication',
    description: 'Redis is accessible without password authentication.',
    assetId: 'svc-003',
    assetName: 'Redis - cache.internal.vn:6379',
    assetType: 'service',
    rule: 'REDIS-001',
    remediation: 'Enable requirepass in redis.conf and use strong passwords.',
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
  },
]

// Combine all findings
export const assetFindings: AssetFinding[] = [
  ...apiFindings,
  ...domainFindings,
  ...websiteFindings,
  ...hostFindings,
  ...containerFindings,
  ...databaseFindings,
  ...mobileFindings,
  ...repositoryFindings,
  ...cloudFindings,
  ...serviceFindings,
]
