/**
 * Host Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const hostAssets: BaseAsset[] = [
  {
    id: "host-001",
    type: "host",
    name: "prod-web-01",
    description: "Production web server",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      ip: "10.0.1.10",
      hostname: "prod-web-01.internal.vn",
      os: "Ubuntu",
      osVersion: "22.04 LTS",
      architecture: "x64",
      cpuCores: 8,
      memoryGB: 32,
      isVirtual: true,
      hypervisor: "VMware ESXi",
      openPorts: [22, 80, 443],
    },
    tags: ["production", "web", "critical"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "host-002",
    type: "host",
    name: "prod-db-01",
    description: "Primary database server",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      ip: "10.0.1.20",
      hostname: "prod-db-01.internal.vn",
      os: "CentOS",
      osVersion: "8.5",
      architecture: "x64",
      cpuCores: 16,
      memoryGB: 64,
      isVirtual: false,
      openPorts: [22, 3306],
    },
    tags: ["production", "database", "critical"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(0),
  },
  {
    id: "host-003",
    type: "host",
    name: "prod-app-01",
    description: "Application server",
    status: "active",
    riskScore: 38,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      ip: "10.0.2.10",
      hostname: "prod-app-01.internal.vn",
      os: "Ubuntu",
      osVersion: "20.04 LTS",
      architecture: "x64",
      cpuCores: 4,
      memoryGB: 16,
      isVirtual: true,
      hypervisor: "KVM",
      openPorts: [22, 8080, 8443],
    },
    tags: ["production", "application"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "host-004",
    type: "host",
    name: "staging-web-01",
    description: "Staging web server",
    status: "active",
    riskScore: 25,
    findingCount: 1,
    groupId: "grp-004",
    groupName: "Staging Environment",
    metadata: {
      ip: "10.1.1.10",
      hostname: "staging-web-01.internal.vn",
      os: "Ubuntu",
      osVersion: "22.04 LTS",
      architecture: "x64",
      cpuCores: 4,
      memoryGB: 8,
      isVirtual: true,
      hypervisor: "VMware ESXi",
      openPorts: [22, 80, 443],
    },
    tags: ["staging", "web"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
  {
    id: "host-005",
    type: "host",
    name: "dc-windows-01",
    description: "Domain controller",
    status: "active",
    riskScore: 85,
    findingCount: 6,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      ip: "10.0.0.5",
      hostname: "dc-windows-01.corp.vn",
      os: "Windows Server",
      osVersion: "2019",
      architecture: "x64",
      cpuCores: 8,
      memoryGB: 32,
      isVirtual: true,
      hypervisor: "Hyper-V",
      openPorts: [53, 88, 389, 636, 3389],
    },
    tags: ["critical", "infrastructure", "windows"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(0),
  },
];
