/**
 * Kubernetes Resources Mock Data
 */

import type { K8sCluster, K8sWorkload, ContainerImage } from "../../types";
import { daysAgo } from "./helpers";

export const k8sClusters: K8sCluster[] = [
  {
    id: "cluster-001",
    name: "prod-gke-cluster",
    provider: "gke",
    version: "1.28.5-gke.1200",
    region: "asia-southeast1",
    nodeCount: 5,
    namespaceCount: 12,
    workloadCount: 45,
    podCount: 156,
    status: "healthy",
    riskScore: 65,
    findingCount: 8,
    apiServerUrl: "https://35.240.10.25",
    createdAt: daysAgo(300),
    lastSeen: daysAgo(0),
  },
  {
    id: "cluster-002",
    name: "staging-eks-cluster",
    provider: "eks",
    version: "1.28",
    region: "ap-southeast-1",
    nodeCount: 3,
    namespaceCount: 6,
    workloadCount: 23,
    podCount: 67,
    status: "healthy",
    riskScore: 42,
    findingCount: 4,
    apiServerUrl: "https://eks.ap-southeast-1.amazonaws.com",
    createdAt: daysAgo(200),
    lastSeen: daysAgo(0),
  },
  {
    id: "cluster-003",
    name: "dev-k3s-cluster",
    provider: "k3s",
    version: "1.27.8+k3s1",
    nodeCount: 2,
    namespaceCount: 4,
    workloadCount: 15,
    podCount: 34,
    status: "warning",
    riskScore: 55,
    findingCount: 6,
    createdAt: daysAgo(150),
    lastSeen: daysAgo(0),
  },
];

export const k8sWorkloads: K8sWorkload[] = [
  {
    id: "workload-001",
    name: "api-gateway",
    type: "deployment",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 3,
    readyReplicas: 3,
    images: ["nginx:1.25-alpine"],
    labels: { app: "api-gateway", tier: "frontend" },
    status: "running",
    riskScore: 42,
    findingCount: 2,
    cpuRequest: "250m",
    cpuLimit: "500m",
    memoryRequest: "256Mi",
    memoryLimit: "512Mi",
    createdAt: daysAgo(180),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-002",
    name: "user-service",
    type: "deployment",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 5,
    readyReplicas: 5,
    images: ["gcr.io/vingroup/user-service:v2.5.1"],
    labels: { app: "user-service", tier: "backend" },
    status: "running",
    riskScore: 55,
    findingCount: 3,
    cpuRequest: "500m",
    cpuLimit: "1000m",
    memoryRequest: "512Mi",
    memoryLimit: "1Gi",
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-003",
    name: "payment-processor",
    type: "deployment",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 3,
    readyReplicas: 3,
    images: ["gcr.io/vingroup/payment-processor:v3.1.0"],
    labels: { app: "payment-processor", tier: "backend", pci: "true" },
    status: "running",
    riskScore: 78,
    findingCount: 5,
    cpuRequest: "1000m",
    cpuLimit: "2000m",
    memoryRequest: "1Gi",
    memoryLimit: "2Gi",
    createdAt: daysAgo(300),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-004",
    name: "redis-cache",
    type: "statefulset",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 3,
    readyReplicas: 3,
    images: ["redis:7.2-alpine"],
    labels: { app: "redis", tier: "cache" },
    status: "running",
    riskScore: 32,
    findingCount: 1,
    cpuRequest: "250m",
    cpuLimit: "500m",
    memoryRequest: "512Mi",
    memoryLimit: "1Gi",
    createdAt: daysAgo(200),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-005",
    name: "fluent-bit",
    type: "daemonset",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "monitoring",
    replicas: 5,
    readyReplicas: 5,
    images: ["fluent/fluent-bit:2.1.10"],
    labels: { app: "fluent-bit", tier: "logging" },
    status: "running",
    riskScore: 18,
    findingCount: 0,
    cpuRequest: "100m",
    cpuLimit: "200m",
    memoryRequest: "128Mi",
    memoryLimit: "256Mi",
    createdAt: daysAgo(100),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-006",
    name: "backup-job",
    type: "cronjob",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 1,
    readyReplicas: 0,
    images: ["gcr.io/vingroup/backup-tool:v1.0.0"],
    labels: { app: "backup", tier: "maintenance" },
    status: "pending",
    riskScore: 25,
    findingCount: 1,
    cpuLimit: "500m",
    memoryLimit: "512Mi",
    createdAt: daysAgo(60),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-007",
    name: "notification-service",
    type: "deployment",
    clusterId: "cluster-002",
    clusterName: "staging-eks-cluster",
    namespace: "staging",
    replicas: 2,
    readyReplicas: 2,
    images: ["gcr.io/vingroup/notification:v1.2.0"],
    labels: { app: "notification", tier: "backend" },
    status: "running",
    riskScore: 35,
    findingCount: 2,
    cpuRequest: "250m",
    cpuLimit: "500m",
    memoryRequest: "256Mi",
    memoryLimit: "512Mi",
    createdAt: daysAgo(90),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-008",
    name: "postgres-db",
    type: "statefulset",
    clusterId: "cluster-002",
    clusterName: "staging-eks-cluster",
    namespace: "staging",
    replicas: 1,
    readyReplicas: 1,
    images: ["postgres:15.4-alpine"],
    labels: { app: "postgres", tier: "database" },
    status: "running",
    riskScore: 45,
    findingCount: 2,
    cpuRequest: "500m",
    cpuLimit: "1000m",
    memoryRequest: "1Gi",
    memoryLimit: "2Gi",
    createdAt: daysAgo(120),
    lastSeen: daysAgo(0),
  },
];

export const containerImages: ContainerImage[] = [
  {
    id: "image-001",
    name: "nginx",
    tag: "1.25-alpine",
    fullName: "nginx:1.25-alpine",
    registry: "docker.io",
    digest: "sha256:a1b2c3d4e5f6...",
    size: 45,
    os: "linux",
    architecture: "amd64",
    workloadCount: 3,
    vulnerabilities: { critical: 0, high: 1, medium: 3, low: 5 },
    riskScore: 35,
    lastScanned: daysAgo(1),
    pushedAt: daysAgo(30),
    createdAt: daysAgo(180),
  },
  {
    id: "image-002",
    name: "vingroup/user-service",
    tag: "v2.5.1",
    fullName: "gcr.io/vingroup/user-service:v2.5.1",
    registry: "gcr.io",
    digest: "sha256:b2c3d4e5f6a7...",
    size: 250,
    os: "linux",
    architecture: "amd64",
    workloadCount: 5,
    vulnerabilities: { critical: 1, high: 3, medium: 8, low: 12 },
    riskScore: 72,
    lastScanned: daysAgo(0),
    pushedAt: daysAgo(7),
    createdAt: daysAgo(250),
  },
  {
    id: "image-003",
    name: "vingroup/payment-processor",
    tag: "v3.1.0",
    fullName: "gcr.io/vingroup/payment-processor:v3.1.0",
    registry: "gcr.io",
    digest: "sha256:c3d4e5f6a7b8...",
    size: 320,
    os: "linux",
    architecture: "amd64",
    workloadCount: 3,
    vulnerabilities: { critical: 2, high: 5, medium: 10, low: 8 },
    riskScore: 85,
    lastScanned: daysAgo(0),
    pushedAt: daysAgo(14),
    createdAt: daysAgo(300),
  },
  {
    id: "image-004",
    name: "redis",
    tag: "7.2-alpine",
    fullName: "redis:7.2-alpine",
    registry: "docker.io",
    digest: "sha256:d4e5f6a7b8c9...",
    size: 35,
    os: "linux",
    architecture: "amd64",
    workloadCount: 4,
    vulnerabilities: { critical: 0, high: 0, medium: 2, low: 3 },
    riskScore: 18,
    lastScanned: daysAgo(2),
    pushedAt: daysAgo(45),
    createdAt: daysAgo(200),
  },
  {
    id: "image-005",
    name: "fluent/fluent-bit",
    tag: "2.1.10",
    fullName: "fluent/fluent-bit:2.1.10",
    registry: "docker.io",
    digest: "sha256:e5f6a7b8c9d0...",
    size: 85,
    os: "linux",
    architecture: "amd64",
    workloadCount: 5,
    vulnerabilities: { critical: 0, high: 0, medium: 1, low: 2 },
    riskScore: 12,
    lastScanned: daysAgo(1),
    pushedAt: daysAgo(60),
    createdAt: daysAgo(100),
  },
  {
    id: "image-006",
    name: "postgres",
    tag: "15.4-alpine",
    fullName: "postgres:15.4-alpine",
    registry: "docker.io",
    digest: "sha256:f6a7b8c9d0e1...",
    size: 120,
    os: "linux",
    architecture: "amd64",
    workloadCount: 2,
    vulnerabilities: { critical: 0, high: 2, medium: 4, low: 6 },
    riskScore: 45,
    lastScanned: daysAgo(1),
    pushedAt: daysAgo(30),
    createdAt: daysAgo(120),
  },
  {
    id: "image-007",
    name: "vingroup/notification",
    tag: "v1.2.0",
    fullName: "gcr.io/vingroup/notification:v1.2.0",
    registry: "gcr.io",
    digest: "sha256:a7b8c9d0e1f2...",
    size: 180,
    os: "linux",
    architecture: "amd64",
    workloadCount: 2,
    vulnerabilities: { critical: 0, high: 1, medium: 5, low: 8 },
    riskScore: 38,
    lastScanned: daysAgo(0),
    pushedAt: daysAgo(21),
    createdAt: daysAgo(90),
  },
];
