/**
 * Mobile App Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const mobileAssets: BaseAsset[] = [
  {
    id: "mobile-001",
    type: "mobile",
    name: "VinBank Mobile",
    description: "Mobile banking application",
    status: "active",
    riskScore: 75,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      platform: "cross-platform",
      bundleId: "vn.vingroup.banking",
      appVersion: "5.2.1",
      buildNumber: "521",
      minSdkVersion: "21",
      targetSdkVersion: "34",
      storeUrl: "https://play.google.com/store/apps/details?id=vn.vingroup.banking",
      lastRelease: daysAgo(14),
      downloads: 5000000,
      rating: 4.5,
      permissions: ["CAMERA", "FINGERPRINT", "LOCATION", "STORAGE"],
      sdks: ["React Native", "Firebase", "Sentry"],
    },
    tags: ["critical", "banking", "customer-facing"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(14),
  },
  {
    id: "mobile-002",
    type: "mobile",
    name: "VinMart Shopping",
    description: "E-commerce shopping app",
    status: "active",
    riskScore: 52,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      platform: "android",
      bundleId: "vn.vinmart.shopping",
      appVersion: "3.8.0",
      buildNumber: "380",
      minSdkVersion: "23",
      targetSdkVersion: "34",
      storeUrl: "https://play.google.com/store/apps/details?id=vn.vinmart.shopping",
      lastRelease: daysAgo(7),
      downloads: 2000000,
      rating: 4.2,
      permissions: ["CAMERA", "LOCATION", "STORAGE", "NOTIFICATIONS"],
      sdks: ["Kotlin", "Firebase", "Google Maps"],
    },
    tags: ["production", "ecommerce"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(7),
  },
  {
    id: "mobile-003",
    type: "mobile",
    name: "VinMart iOS",
    description: "VinMart iOS application",
    status: "active",
    riskScore: 48,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      platform: "ios",
      bundleId: "vn.vinmart.ios",
      appVersion: "3.7.5",
      buildNumber: "375",
      minSdkVersion: "14.0",
      targetSdkVersion: "17.0",
      storeUrl: "https://apps.apple.com/vn/app/vinmart/id123456789",
      lastRelease: daysAgo(10),
      downloads: 800000,
      rating: 4.4,
      permissions: ["Camera", "Location", "Photos", "Notifications"],
      sdks: ["Swift", "Firebase", "MapKit"],
    },
    tags: ["production", "ios", "ecommerce"],
    firstSeen: daysAgo(280),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(280),
    updatedAt: daysAgo(10),
  },
  {
    id: "mobile-004",
    type: "mobile",
    name: "Internal OPS App",
    description: "Internal operations app",
    status: "active",
    riskScore: 32,
    findingCount: 1,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      platform: "android",
      bundleId: "vn.vingroup.ops",
      appVersion: "1.5.0",
      buildNumber: "150",
      minSdkVersion: "26",
      targetSdkVersion: "34",
      lastRelease: daysAgo(30),
      downloads: 500,
      rating: 4.0,
      permissions: ["CAMERA", "LOCATION"],
      sdks: ["Flutter", "Firebase"],
    },
    tags: ["internal", "operations"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(30),
  },
  {
    id: "mobile-005",
    type: "mobile",
    name: "Partner Portal",
    description: "Partner mobile portal",
    status: "pending",
    riskScore: 25,
    findingCount: 0,
    groupId: "grp-005",
    groupName: "Partner Systems",
    metadata: {
      platform: "cross-platform",
      bundleId: "vn.vingroup.partner",
      appVersion: "1.0.0-beta",
      buildNumber: "100",
      minSdkVersion: "21",
      targetSdkVersion: "34",
      lastRelease: daysAgo(60),
      downloads: 100,
      permissions: ["CAMERA", "STORAGE"],
      sdks: ["React Native", "Firebase"],
    },
    tags: ["beta", "partner"],
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
];
