/**
 * Service Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const serviceAssets: BaseAsset[] = [
  {
    id: "svc-001",
    type: "service",
    name: "SSH - 192.168.1.10:22",
    description: "Production SSH Server",
    status: "active",
    riskScore: 25,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      port: 22,
      protocol: "SSH",
      version: "OpenSSH 8.9",
      banner: "SSH-2.0-OpenSSH_8.9",
    },
    tags: ["production", "infrastructure"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "svc-002",
    type: "service",
    name: "MySQL - db.internal.vn:3306",
    description: "Primary Database Server",
    status: "active",
    riskScore: 68,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      port: 3306,
      protocol: "MySQL",
      version: "MySQL 8.0.32",
    },
    tags: ["critical", "database"],
    firstSeen: daysAgo(450),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(450),
    updatedAt: daysAgo(0),
  },
  {
    id: "svc-003",
    type: "service",
    name: "Redis - cache.internal.vn:6379",
    description: "Redis Cache Cluster",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      port: 6379,
      protocol: "Redis",
      version: "Redis 7.0.11",
    },
    tags: ["production", "cache"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "svc-004",
    type: "service",
    name: "Kafka - kafka.internal.vn:9092",
    description: "Message Queue Cluster",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      port: 9092,
      protocol: "Kafka",
      version: "Apache Kafka 3.5.0",
    },
    tags: ["production", "messaging"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "svc-005",
    type: "service",
    name: "Elasticsearch - es.internal.vn:9200",
    description: "Log Search Cluster",
    status: "active",
    riskScore: 38,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      port: 9200,
      protocol: "HTTP/Elasticsearch",
      version: "Elasticsearch 8.10.0",
    },
    tags: ["production", "logging"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
];
