/**
 * Serverless Function Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const serverlessAssets: BaseAsset[] = [
  {
    id: "serverless-001",
    type: "serverless",
    name: "payment-processor",
    description: "Payment processing Lambda function",
    status: "active",
    riskScore: 78,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      functionName: "payment-processor",
      functionRuntime: "nodejs20.x",
      functionHandler: "index.handler",
      functionMemory: 512,
      functionTimeout: 30,
      functionCodeSize: 2048,
      functionLastModified: daysAgo(5),
      functionTriggers: ["API Gateway", "SQS"],
      functionEnvVars: 8,
      functionLayers: ["aws-sdk-layer", "crypto-layer"],
      functionVpcEnabled: true,
      cloudProvider: "aws",
      region: "ap-southeast-1",
    },
    tags: ["critical", "production", "banking", "pci-dss"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(5),
  },
  {
    id: "serverless-002",
    type: "serverless",
    name: "notification-sender",
    description: "Push notification Cloud Function",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      functionName: "notification-sender",
      functionRuntime: "python311",
      functionHandler: "main.send_notification",
      functionMemory: 256,
      functionTimeout: 15,
      functionCodeSize: 1024,
      functionLastModified: daysAgo(12),
      functionTriggers: ["Pub/Sub", "Cloud Scheduler"],
      functionEnvVars: 5,
      functionLayers: [],
      functionVpcEnabled: false,
      cloudProvider: "gcp",
      region: "asia-southeast1",
    },
    tags: ["production", "notifications"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(12),
  },
  {
    id: "serverless-003",
    type: "serverless",
    name: "image-resizer",
    description: "S3 triggered image resize function",
    status: "active",
    riskScore: 25,
    findingCount: 1,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      functionName: "image-resizer",
      functionRuntime: "nodejs18.x",
      functionHandler: "resize.handler",
      functionMemory: 1024,
      functionTimeout: 60,
      functionCodeSize: 3072,
      functionLastModified: daysAgo(30),
      functionTriggers: ["S3"],
      functionEnvVars: 3,
      functionLayers: ["sharp-layer"],
      functionVpcEnabled: false,
      cloudProvider: "aws",
      region: "ap-southeast-1",
    },
    tags: ["production", "media"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(30),
  },
  {
    id: "serverless-004",
    type: "serverless",
    name: "kyc-verification",
    description: "KYC document verification Azure Function",
    status: "active",
    riskScore: 85,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      functionName: "kyc-verification",
      functionRuntime: "dotnet8",
      functionHandler: "KycVerification.Run",
      functionMemory: 768,
      functionTimeout: 45,
      functionCodeSize: 4096,
      functionLastModified: daysAgo(3),
      functionTriggers: ["HTTP", "Blob Storage"],
      functionEnvVars: 12,
      functionLayers: [],
      functionVpcEnabled: true,
      cloudProvider: "azure",
      region: "southeastasia",
    },
    tags: ["critical", "production", "banking", "kyc"],
    firstSeen: daysAgo(120),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },
  {
    id: "serverless-005",
    type: "serverless",
    name: "order-processor",
    description: "Order processing event handler",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      functionName: "order-processor",
      functionRuntime: "python39",
      functionHandler: "order.process",
      functionMemory: 512,
      functionTimeout: 30,
      functionCodeSize: 1536,
      functionLastModified: daysAgo(7),
      functionTriggers: ["EventBridge", "DynamoDB Streams"],
      functionEnvVars: 6,
      functionLayers: ["boto3-layer"],
      functionVpcEnabled: true,
      cloudProvider: "aws",
      region: "ap-southeast-1",
    },
    tags: ["production", "ecommerce", "orders"],
    firstSeen: daysAgo(90),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(7),
  },
  {
    id: "serverless-006",
    type: "serverless",
    name: "fraud-detector",
    description: "Real-time fraud detection function",
    status: "active",
    riskScore: 92,
    findingCount: 6,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      functionName: "fraud-detector",
      functionRuntime: "java17",
      functionHandler: "FraudDetector::handleRequest",
      functionMemory: 2048,
      functionTimeout: 10,
      functionCodeSize: 8192,
      functionLastModified: daysAgo(2),
      functionTriggers: ["Kinesis", "API Gateway"],
      functionEnvVars: 15,
      functionLayers: ["ml-model-layer"],
      functionVpcEnabled: true,
      cloudProvider: "aws",
      region: "ap-southeast-1",
    },
    tags: ["critical", "production", "banking", "ml", "security"],
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: "serverless-007",
    type: "serverless",
    name: "report-generator",
    description: "Scheduled report generation Cloud Run job",
    status: "active",
    riskScore: 35,
    findingCount: 1,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      functionName: "report-generator",
      functionRuntime: "python311",
      functionHandler: "reports.generate",
      functionMemory: 4096,
      functionTimeout: 300,
      functionCodeSize: 2560,
      functionLastModified: daysAgo(14),
      functionTriggers: ["Cloud Scheduler"],
      functionEnvVars: 8,
      functionLayers: [],
      functionVpcEnabled: false,
      cloudProvider: "gcp",
      region: "asia-southeast1",
    },
    tags: ["internal", "reports"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(14),
  },
  {
    id: "serverless-008",
    type: "serverless",
    name: "staging-api-handler",
    description: "Staging API request handler",
    status: "active",
    riskScore: 30,
    findingCount: 2,
    groupId: "grp-004",
    groupName: "Staging Environment",
    metadata: {
      functionName: "staging-api-handler",
      functionRuntime: "nodejs20.x",
      functionHandler: "api.handler",
      functionMemory: 256,
      functionTimeout: 15,
      functionCodeSize: 1024,
      functionLastModified: daysAgo(1),
      functionTriggers: ["API Gateway"],
      functionEnvVars: 4,
      functionLayers: [],
      functionVpcEnabled: false,
      cloudProvider: "aws",
      region: "ap-southeast-1",
    },
    tags: ["staging", "testing"],
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
  {
    id: "serverless-009",
    type: "serverless",
    name: "data-exporter",
    description: "Data export to external systems",
    status: "inactive",
    riskScore: 48,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      functionName: "data-exporter",
      functionRuntime: "go1.x",
      functionHandler: "main",
      functionMemory: 512,
      functionTimeout: 120,
      functionCodeSize: 3584,
      functionLastModified: daysAgo(60),
      functionTriggers: ["EventBridge"],
      functionEnvVars: 6,
      functionLayers: [],
      functionVpcEnabled: true,
      cloudProvider: "aws",
      region: "ap-southeast-1",
    },
    tags: ["internal", "data", "deprecated"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(30),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(60),
  },
  {
    id: "serverless-010",
    type: "serverless",
    name: "audit-logger",
    description: "Security audit logging function",
    status: "active",
    riskScore: 65,
    findingCount: 3,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      functionName: "audit-logger",
      functionRuntime: "nodejs20.x",
      functionHandler: "audit.log",
      functionMemory: 256,
      functionTimeout: 5,
      functionCodeSize: 512,
      functionLastModified: daysAgo(10),
      functionTriggers: ["CloudWatch Logs", "SNS"],
      functionEnvVars: 4,
      functionLayers: [],
      functionVpcEnabled: false,
      cloudProvider: "aws",
      region: "ap-southeast-1",
    },
    tags: ["production", "security", "audit"],
    firstSeen: daysAgo(240),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(240),
    updatedAt: daysAgo(10),
  },
];
