/**
 * Website Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const websiteAssets: BaseAsset[] = [
  {
    id: "web-001",
    type: "website",
    name: "portal.fpt.com.vn",
    description: "FPT Customer Portal",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      technology: ["React", "Node.js", "PostgreSQL"],
      ssl: true,
      sslExpiry: "2025-06-15",
      httpStatus: 200,
    },
    tags: ["production", "customer-facing"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(1),
  },
  {
    id: "web-002",
    type: "website",
    name: "ebanking.techcombank.com.vn",
    description: "Techcombank Internet Banking",
    status: "active",
    riskScore: 88,
    findingCount: 6,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      technology: ["Angular", "Java Spring", "Oracle"],
      ssl: true,
      sslExpiry: "2025-04-20",
      httpStatus: 200,
    },
    tags: ["critical", "banking", "customer-facing"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(0),
  },
  {
    id: "web-003",
    type: "website",
    name: "shop.vinmart.vn",
    description: "VinMart E-commerce",
    status: "active",
    riskScore: 52,
    findingCount: 4,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      technology: ["Vue.js", "PHP Laravel", "MySQL"],
      ssl: true,
      sslExpiry: "2025-08-10",
      httpStatus: 200,
    },
    tags: ["production", "e-commerce"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
  },
  {
    id: "web-004",
    type: "website",
    name: "api.momo.vn",
    description: "MoMo API Gateway",
    status: "active",
    riskScore: 78,
    findingCount: 5,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      technology: ["Go", "gRPC", "Redis"],
      ssl: true,
      sslExpiry: "2025-09-25",
      httpStatus: 200,
    },
    tags: ["critical", "api", "payment"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(1),
  },
  {
    id: "web-005",
    type: "website",
    name: "admin.vnpt.vn",
    description: "VNPT Admin Portal",
    status: "active",
    riskScore: 35,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      technology: ["React", "Python Django", "PostgreSQL"],
      ssl: true,
      sslExpiry: "2025-07-30",
      httpStatus: 200,
    },
    tags: ["internal", "admin"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
];
