/**
 * Crown Jewels Mock Data
 */

import type { CrownJewel, CrownJewelStats, CrownJewelDependency } from "../types";

const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

export const mockCrownJewels: CrownJewel[] = [
  {
    id: "cj-001",
    name: "Customer Database",
    description: "Primary customer data store containing PII and financial records",
    category: "data",
    protectionLevel: "maximum",
    dataClassification: "top_secret",
    status: "protected",
    businessImpact: "Complete business disruption if compromised. Regulatory penalties up to $50M.",
    owner: "Nguyen Van An",
    ownerEmail: "an.nguyen@company.vn",
    businessUnit: "Technology & Engineering",
    riskScore: 85,
    exposureCount: 2,
    dependencyCount: 12,
    lastAssessed: daysAgo(7),
    tags: ["pii", "gdpr", "critical"],
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: "cj-002",
    name: "Payment Processing System",
    description: "Core payment gateway and transaction processing engine",
    category: "system",
    protectionLevel: "maximum",
    dataClassification: "top_secret",
    status: "protected",
    businessImpact: "Revenue loss of $2M/hour if unavailable. PCI-DSS compliance violation.",
    owner: "Tran Thi Binh",
    ownerEmail: "binh.tran@company.vn",
    businessUnit: "Finance & Accounting",
    riskScore: 92,
    exposureCount: 1,
    dependencyCount: 8,
    lastAssessed: daysAgo(3),
    tags: ["pci-dss", "financial", "core"],
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "cj-003",
    name: "Source Code Repository",
    description: "Main codebase containing proprietary algorithms and business logic",
    category: "intellectual_property",
    protectionLevel: "high",
    dataClassification: "confidential",
    status: "at_risk",
    businessImpact: "Competitive advantage loss. IP theft could cost $20M+.",
    owner: "Le Van Cuong",
    ownerEmail: "cuong.le@company.vn",
    businessUnit: "Technology & Engineering",
    riskScore: 78,
    exposureCount: 5,
    dependencyCount: 45,
    lastAssessed: daysAgo(14),
    tags: ["ip", "code", "proprietary"],
    createdAt: daysAgo(365),
    updatedAt: daysAgo(5),
  },
  {
    id: "cj-004",
    name: "Authentication Service",
    description: "Central identity and access management system",
    category: "application",
    protectionLevel: "maximum",
    dataClassification: "confidential",
    status: "protected",
    businessImpact: "All services dependent. Compromise affects entire platform.",
    owner: "Pham Thi Dung",
    ownerEmail: "dung.pham@company.vn",
    businessUnit: "Technology & Engineering",
    riskScore: 88,
    exposureCount: 0,
    dependencyCount: 28,
    lastAssessed: daysAgo(5),
    tags: ["auth", "iam", "security"],
    createdAt: daysAgo(280),
    updatedAt: daysAgo(1),
  },
  {
    id: "cj-005",
    name: "Financial Records Database",
    description: "Accounting, audit trails, and financial reporting data",
    category: "financial",
    protectionLevel: "maximum",
    dataClassification: "top_secret",
    status: "protected",
    businessImpact: "Regulatory violations. Audit failure. $10M+ penalties.",
    owner: "Tran Thi Binh",
    ownerEmail: "binh.tran@company.vn",
    businessUnit: "Finance & Accounting",
    riskScore: 75,
    exposureCount: 0,
    dependencyCount: 6,
    lastAssessed: daysAgo(10),
    tags: ["sox", "audit", "financial"],
    createdAt: daysAgo(365),
    updatedAt: daysAgo(3),
  },
  {
    id: "cj-006",
    name: "Production Kubernetes Cluster",
    description: "Main container orchestration platform running all production services",
    category: "infrastructure",
    protectionLevel: "high",
    dataClassification: "confidential",
    status: "at_risk",
    businessImpact: "Total service outage. Revenue impact $500K/hour.",
    owner: "Pham Van Nam",
    ownerEmail: "nam.pham@company.vn",
    businessUnit: "IT Infrastructure",
    riskScore: 82,
    exposureCount: 3,
    dependencyCount: 67,
    lastAssessed: daysAgo(2),
    tags: ["k8s", "production", "infrastructure"],
    createdAt: daysAgo(200),
    updatedAt: daysAgo(1),
  },
  {
    id: "cj-007",
    name: "HR Employee Database",
    description: "Employee records including salary, performance, and personal data",
    category: "data",
    protectionLevel: "high",
    dataClassification: "confidential",
    status: "protected",
    businessImpact: "GDPR violation. Employee trust loss. Legal liability.",
    owner: "Le Van Cuong",
    ownerEmail: "cuong.le@company.vn",
    businessUnit: "Human Resources",
    riskScore: 65,
    exposureCount: 0,
    dependencyCount: 4,
    lastAssessed: daysAgo(20),
    tags: ["pii", "hr", "employee"],
    createdAt: daysAgo(365),
    updatedAt: daysAgo(10),
  },
  {
    id: "cj-008",
    name: "API Gateway",
    description: "Central API management and routing system",
    category: "application",
    protectionLevel: "high",
    dataClassification: "internal",
    status: "exposed",
    businessImpact: "API availability affects all clients. SLA violations.",
    owner: "Hoang Thi Oanh",
    ownerEmail: "oanh.hoang@company.vn",
    businessUnit: "Technology & Engineering",
    riskScore: 72,
    exposureCount: 8,
    dependencyCount: 35,
    lastAssessed: daysAgo(1),
    tags: ["api", "gateway", "public"],
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "cj-009",
    name: "Encryption Key Management",
    description: "HSM and key management system for all cryptographic operations",
    category: "infrastructure",
    protectionLevel: "maximum",
    dataClassification: "top_secret",
    status: "protected",
    businessImpact: "Compromise exposes all encrypted data. Catastrophic breach.",
    owner: "Pham Van Nam",
    ownerEmail: "nam.pham@company.vn",
    businessUnit: "IT Infrastructure",
    riskScore: 95,
    exposureCount: 0,
    dependencyCount: 18,
    lastAssessed: daysAgo(7),
    tags: ["hsm", "encryption", "keys"],
    createdAt: daysAgo(365),
    updatedAt: daysAgo(2),
  },
  {
    id: "cj-010",
    name: "Trading Algorithm Engine",
    description: "Proprietary trading algorithms and market analysis models",
    category: "intellectual_property",
    protectionLevel: "maximum",
    dataClassification: "top_secret",
    status: "under_review",
    businessImpact: "Core competitive advantage. Loss could end business.",
    owner: "Vu Van Phuc",
    ownerEmail: "phuc.vu@company.vn",
    businessUnit: "Research & Development",
    riskScore: 90,
    exposureCount: 1,
    dependencyCount: 5,
    lastAssessed: daysAgo(30),
    tags: ["algorithm", "trading", "ml"],
    createdAt: daysAgo(150),
    updatedAt: daysAgo(15),
  },
];

export const mockDependencies: CrownJewelDependency[] = [
  {
    id: "dep-001",
    jewelId: "cj-001",
    dependsOnId: "cj-004",
    dependsOnName: "Authentication Service",
    dependencyType: "upstream",
    criticality: "critical",
  },
  {
    id: "dep-002",
    jewelId: "cj-002",
    dependsOnId: "cj-001",
    dependsOnName: "Customer Database",
    dependencyType: "upstream",
    criticality: "critical",
  },
  {
    id: "dep-003",
    jewelId: "cj-002",
    dependsOnId: "cj-009",
    dependsOnName: "Encryption Key Management",
    dependencyType: "upstream",
    criticality: "critical",
  },
];

export const getCrownJewelById = (id: string): CrownJewel | undefined => {
  return mockCrownJewels.find((cj) => cj.id === id);
};

export const getCrownJewels = (): CrownJewel[] => {
  return [...mockCrownJewels];
};

export const getDependencies = (jewelId: string): CrownJewelDependency[] => {
  return mockDependencies.filter((d) => d.jewelId === jewelId);
};

export const getCrownJewelStats = (): CrownJewelStats => {
  const jewels = mockCrownJewels;
  return {
    total: jewels.length,
    byStatus: {
      protected: jewels.filter((j) => j.status === "protected").length,
      at_risk: jewels.filter((j) => j.status === "at_risk").length,
      exposed: jewels.filter((j) => j.status === "exposed").length,
      under_review: jewels.filter((j) => j.status === "under_review").length,
    },
    byProtectionLevel: {
      maximum: jewels.filter((j) => j.protectionLevel === "maximum").length,
      high: jewels.filter((j) => j.protectionLevel === "high").length,
      standard: jewels.filter((j) => j.protectionLevel === "standard").length,
      basic: jewels.filter((j) => j.protectionLevel === "basic").length,
    },
    byCategory: {
      data: jewels.filter((j) => j.category === "data").length,
      system: jewels.filter((j) => j.category === "system").length,
      application: jewels.filter((j) => j.category === "application").length,
      infrastructure: jewels.filter((j) => j.category === "infrastructure").length,
      intellectual_property: jewels.filter((j) => j.category === "intellectual_property").length,
      financial: jewels.filter((j) => j.category === "financial").length,
    },
    totalExposures: jewels.reduce((acc, j) => acc + j.exposureCount, 0),
    averageRiskScore: Math.round(
      jewels.reduce((acc, j) => acc + j.riskScore, 0) / jewels.length
    ),
  };
};
