/**
 * Scan Mock Data
 *
 * Scan data for development and testing
 */

import type { Scan, ScanStats } from '../types'

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

export const mockScans: Scan[] = [
  {
    id: 'scan-001',
    name: 'Weekly Full Scan - Production',
    description: 'Scheduled weekly vulnerability scan for production environment',
    type: 'full',
    status: 'active',
    targets: {
      type: 'asset_groups',
      assetGroupIds: ['grp-001', 'grp-002'],
      assetIds: [],
      assetNames: {},
      customTargets: [],
    },
    targetCount: 68,
    progress: 67,
    options: {
      portScanning: true,
      webAppScanning: true,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: true,
    },
    intensity: 'medium',
    maxConcurrent: 10,
    findingsCount: 8,
    criticalCount: 1,
    highCount: 3,
    mediumCount: 3,
    lowCount: 1,
    startedAt: daysAgo(0),
    schedule: {
      runImmediately: false,
      frequency: 'weekly',
      dayOfWeek: 1,
      time: '02:00',
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: true,
    },
    createdBy: 'usr-001',
    createdByName: 'Nguyen Van An',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(0),
    // Platform agent
    agentPreference: 'platform',
    agentType: 'platform',
    agentId: 'agent-platform-us-east-1',
    agentName: 'Platform Agent US-East-1',
  },
  {
    id: 'scan-002',
    name: 'Quick Scan - E-commerce',
    description: 'Fast check for critical issues on e-commerce sites',
    type: 'quick',
    status: 'completed',
    targets: {
      type: 'asset_groups',
      assetGroupIds: ['grp-003'],
      assetIds: [],
      assetNames: {},
      customTargets: [],
    },
    targetCount: 23,
    progress: 100,
    options: {
      portScanning: false,
      webAppScanning: true,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: false,
    },
    intensity: 'low',
    maxConcurrent: 5,
    findingsCount: 2,
    criticalCount: 0,
    highCount: 1,
    mediumCount: 1,
    lowCount: 0,
    startedAt: daysAgo(2),
    completedAt: daysAgo(2),
    duration: 1800,
    schedule: {
      runImmediately: true,
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: false,
    },
    createdBy: 'usr-002',
    createdByName: 'Tran Thi Binh',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    // Tenant agent
    agentPreference: 'tenant',
    agentType: 'tenant',
    agentId: 'agent-tenant-001',
    agentName: 'Tenant Agent 1',
  },
  {
    id: 'scan-003',
    name: 'Compliance Scan - PCI DSS',
    description: 'PCI DSS compliance audit for payment systems',
    type: 'compliance',
    status: 'completed',
    targets: {
      type: 'asset_groups',
      assetGroupIds: ['grp-001'],
      assetIds: [],
      assetNames: {},
      customTargets: [],
    },
    targetCount: 45,
    progress: 100,
    options: {
      portScanning: true,
      webAppScanning: true,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: true,
    },
    intensity: 'high',
    maxConcurrent: 15,
    findingsCount: 5,
    criticalCount: 0,
    highCount: 2,
    mediumCount: 2,
    lowCount: 1,
    startedAt: daysAgo(5),
    completedAt: daysAgo(5),
    duration: 3600,
    schedule: {
      runImmediately: false,
      frequency: 'monthly',
      dayOfWeek: 1,
      time: '03:00',
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: true,
    },
    createdBy: 'usr-003',
    createdByName: 'Le Van Cuong',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    // Platform agent
    agentPreference: 'auto',
    agentType: 'platform',
    agentId: 'agent-platform-ap-southeast-1',
    agentName: 'Platform Agent AP-Southeast-1',
  },
  {
    id: 'scan-004',
    name: 'Custom Scan - API Security',
    description: 'Custom API security testing for customer-facing APIs',
    type: 'custom',
    status: 'active',
    targets: {
      type: 'individual',
      assetGroupIds: [],
      assetIds: ['asset-010', 'asset-011', 'asset-012'],
      assetNames: {
        'asset-010': 'api.example.com',
        'asset-011': 'api-v2.example.com',
        'asset-012': 'api-internal.example.com',
      },
      customTargets: [],
    },
    targetCount: 3,
    progress: 35,
    options: {
      portScanning: false,
      webAppScanning: false,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: true,
    },
    intensity: 'medium',
    maxConcurrent: 5,
    findingsCount: 4,
    criticalCount: 1,
    highCount: 2,
    mediumCount: 1,
    lowCount: 0,
    startedAt: daysAgo(0),
    schedule: {
      runImmediately: true,
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: true,
    },
    createdBy: 'usr-004',
    createdByName: 'Pham Thi Dung',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
    // Tenant agent
    agentPreference: 'tenant',
    agentType: 'tenant',
    agentId: 'agent-tenant-002',
    agentName: 'Tenant Agent 2',
  },
  {
    id: 'scan-005',
    name: 'Full Scan - Cloud Infrastructure',
    description: 'Complete vulnerability assessment for cloud assets',
    type: 'full',
    status: 'completed',
    targets: {
      type: 'asset_groups',
      assetGroupIds: ['grp-007'],
      assetIds: [],
      assetNames: {},
      customTargets: [],
    },
    targetCount: 35,
    progress: 100,
    options: {
      portScanning: true,
      webAppScanning: true,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: true,
    },
    intensity: 'high',
    maxConcurrent: 20,
    findingsCount: 3,
    criticalCount: 2,
    highCount: 1,
    mediumCount: 0,
    lowCount: 0,
    startedAt: daysAgo(3),
    completedAt: daysAgo(3),
    duration: 7200,
    schedule: {
      runImmediately: true,
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: true,
    },
    createdBy: 'usr-001',
    createdByName: 'Nguyen Van An',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    // Platform agent
    agentPreference: 'platform',
    agentType: 'platform',
    agentId: 'agent-platform-us-west-2',
    agentName: 'Platform Agent US-West-2',
  },
  {
    id: 'scan-006',
    name: 'Quick Scan - Staging Environment',
    description: 'Fast security check before production deployment',
    type: 'quick',
    status: 'pending',
    targets: {
      type: 'asset_groups',
      assetGroupIds: ['grp-004'],
      assetIds: [],
      assetNames: {},
      customTargets: [],
    },
    targetCount: 28,
    progress: 0,
    options: {
      portScanning: true,
      webAppScanning: true,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: false,
    },
    intensity: 'low',
    maxConcurrent: 10,
    findingsCount: 0,
    criticalCount: 0,
    highCount: 0,
    mediumCount: 0,
    lowCount: 0,
    schedule: {
      runImmediately: false,
      frequency: 'daily',
      time: '06:00',
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: false,
    },
    createdBy: 'usr-002',
    createdByName: 'Tran Thi Binh',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    // Pending platform job with queue position
    agentPreference: 'platform',
    queuePosition: 3,
  },
  {
    id: 'scan-007',
    name: 'Monthly Compliance - ISO 27001',
    description: 'Monthly ISO 27001 compliance audit',
    type: 'compliance',
    status: 'completed',
    targets: {
      type: 'custom',
      assetGroupIds: [],
      assetIds: [],
      assetNames: {},
      customTargets: ['vingroup.vn', 'fpt.com.vn', 'techcombank.com.vn', '10.0.0.0/24'],
    },
    targetCount: 259,
    progress: 100,
    options: {
      portScanning: true,
      webAppScanning: true,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: true,
    },
    intensity: 'high',
    maxConcurrent: 25,
    findingsCount: 24,
    criticalCount: 4,
    highCount: 8,
    mediumCount: 7,
    lowCount: 5,
    startedAt: daysAgo(7),
    completedAt: daysAgo(6),
    duration: 86400,
    schedule: {
      runImmediately: false,
      frequency: 'monthly',
      dayOfWeek: 1,
      time: '00:00',
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: true,
    },
    createdBy: 'usr-003',
    createdByName: 'Le Van Cuong',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
    // Auto preference selected tenant agent
    agentPreference: 'auto',
    agentType: 'tenant',
    agentId: 'agent-tenant-001',
    agentName: 'Tenant Agent 1',
  },
  {
    id: 'scan-008',
    name: 'Custom Scan - Partner Integration',
    description: 'Security validation for partner API integrations',
    type: 'custom',
    status: 'failed',
    targets: {
      type: 'custom',
      assetGroupIds: [],
      assetIds: [],
      assetNames: {},
      customTargets: ['partner-api.company.vn', 'integration.partner.com'],
    },
    targetCount: 2,
    progress: 45,
    options: {
      portScanning: false,
      webAppScanning: true,
      sslAnalysis: true,
      bruteForce: false,
      techDetection: true,
      apiSecurity: true,
    },
    intensity: 'medium',
    maxConcurrent: 5,
    findingsCount: 0,
    criticalCount: 0,
    highCount: 0,
    mediumCount: 0,
    lowCount: 0,
    startedAt: daysAgo(4),
    schedule: {
      runImmediately: true,
    },
    notifications: {
      notifyOnComplete: true,
      autoCreateTasks: false,
    },
    createdBy: 'usr-004',
    createdByName: 'Pham Thi Dung',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    // Failed tenant agent job
    agentPreference: 'tenant',
    agentType: 'tenant',
    agentId: 'agent-tenant-002',
    agentName: 'Tenant Agent 2',
  },
]

// Stats
export const getScanStats = (): ScanStats => ({
  totalScans: mockScans.length,
  activeScans: mockScans.filter((s) => s.status === 'active').length,
  completedScans: mockScans.filter((s) => s.status === 'completed').length,
  failedScans: mockScans.filter((s) => s.status === 'failed').length,
  scheduledScans: mockScans.filter((s) => s.status === 'pending').length,
  totalFindings: mockScans.reduce((acc, s) => acc + s.findingsCount, 0),
  averageDuration: Math.round(
    mockScans.filter((s) => s.duration).reduce((acc, s) => acc + (s.duration || 0), 0) /
      mockScans.filter((s) => s.duration).length
  ),
})

// Active scans only
export const getActiveScans = () => mockScans.filter((s) => s.status === 'active')

// Scheduled scans only
export const getScheduledScans = () => mockScans.filter((s) => s.status === 'pending')
