#!/usr/bin/env bash
#
# release-branch.sh — build a release branch that can actually merge into main.
#
# WHY THIS EXISTS: releases here are squash-merged, so main's HEAD ends up with a
# single parent and git cannot see that develop already contains it. The next
# release then reports dozens of conflicting files that are not disagreements at
# all — 27 of them the first time this was hit, in files neither side had
# meaningfully diverged on.
#
# Merging main back into develop is the textbook answer and it does not stick:
# the following release squashes again and the ancestry breaks again. It has
# broken four times.
#
# So this stops fighting the merge strategy. The branch carries its own
# ancestry: develop's tree byte-for-byte, plus one `merge -s ours` commit that
# records main as a parent. It merges cleanly no matter which button anyone
# presses, and it costs one command instead of one careful afternoon.
#
# Usage:
#   scripts/release-branch.sh v0.5.0
#   scripts/release-branch.sh v0.5.0 --push
set -euo pipefail

VERSION="${1:-}"
PUSH="${2:-}"

if [[ -z "$VERSION" ]]; then
  echo "usage: $0 <version> [--push]     e.g. $0 v0.5.0" >&2
  exit 2
fi
if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
  echo "error: version should look like v1.2.3, got '$VERSION'" >&2
  exit 2
fi

BRANCH="release/${VERSION}"
git fetch --quiet origin '+refs/heads/*:refs/remotes/origin/*'

# ── The precondition that makes `-s ours` honest ────────────────────────────
#
# `-s ours` discards main's side entirely. That is only safe if develop already
# contains everything main has. Check it rather than assume it: if someone
# hotfixed main directly, this is the one thing standing between that fix and
# oblivion.
only_in_main="$(git diff --name-status origin/develop origin/main | awk '$1=="A"' | wc -l)"
if [[ "$only_in_main" -ne 0 ]]; then
  echo "REFUSING: $only_in_main file(s) exist in main but not in develop." >&2
  echo "-s ours would silently drop them. Merge main into develop first:" >&2
  git diff --name-status origin/develop origin/main | awk '$1=="A"{print "  "$2}' >&2
  exit 1
fi

if git rev-parse --verify --quiet "origin/${BRANCH}" >/dev/null; then
  echo "REFUSING: origin/${BRANCH} already exists." >&2
  echo "Delete it, or pick another version — this script will not force-push." >&2
  exit 1
fi

git branch -f "$BRANCH" origin/develop
worktree="$(mktemp -d)"
trap 'git worktree remove --force "$worktree" >/dev/null 2>&1 || true' EXIT
git worktree add --quiet "$worktree" "$BRANCH"

git -C "$worktree" merge -s ours --no-edit origin/main -m "chore(release): carry main's ancestry into ${VERSION}

The previous release was squash-merged, so main's HEAD has a single parent and
git cannot see that develop already contains it. Without this commit, merging
develop into main reports conflicts that are not real disagreements.

-s ours keeps develop's tree byte-for-byte and only records main as a parent.
Generated by scripts/release-branch.sh." >/dev/null

# ── Verify, don't assert ────────────────────────────────────────────────────
tree_branch="$(git -C "$worktree" rev-parse 'HEAD^{tree}')"
tree_develop="$(git rev-parse 'origin/develop^{tree}')"
if [[ "$tree_branch" != "$tree_develop" ]]; then
  echo "REFUSING: the release branch tree differs from develop. Not pushing." >&2
  exit 1
fi
if ! git -C "$worktree" merge-base --is-ancestor origin/main HEAD; then
  echo "REFUSING: main is still not an ancestor. The merge did not take." >&2
  exit 1
fi

echo "${BRANCH} built:"
echo "  tree identical to develop  : yes"
echo "  main recorded as an ancestor: yes"
echo "  files in main absent from develop: 0"

if [[ "$PUSH" == "--push" ]]; then
  git push --quiet -u origin "$BRANCH"
  echo "  pushed"
  echo
  echo "Next: open a PR from ${BRANCH} into main, merge it, then tag ${VERSION} on main."
  echo "Prefer a merge commit — a squash leaves main single-parent and the next"
  echo "release needs this script again."
else
  echo
  echo "Not pushed. Re-run with --push when you are ready."
fi
